import {useEffect,useState} from 'react'
import {Columns3,RefreshCw} from 'lucide-react'
import {Badge,Button,Checkbox} from './primitives'
import {DataTable,Pagination} from './data-table'
import type {DataColumn,TableSort} from './data-table'
import {MorphDialog,MorphDialogTrigger,MorphDialogContent,MorphDialogTitle,MorphDialogDescription,MorphDialogClose} from './morph-dialog'
type Row={id:string;name:string;reason:string;amount:number;date:string;status:string}
type Query={page:number;sort:TableSort|null}
const columns:DataColumn<Row>[]=[{key:'id',header:'编号',cell:r=><span className="wo-table-id">{r.id}</span>},{key:'name',header:'申请人',cell:r=><span className="wo-table-person"><span aria-hidden="true">{r.name.slice(0,1)}</span>{r.name}</span>,dataType:'text'},{key:'reason',header:'事由',cell:r=>r.reason,dataType:'text'},{key:'amount',header:'金额',cell:r=>`¥ ${r.amount.toLocaleString('en-US',{minimumFractionDigits:2})}`,dataType:'number',sortable:true,align:'end'},{key:'date',header:'申请日期',cell:r=>r.date,dataType:'time',sortable:true},{key:'status',header:'状态',cell:r=><Badge tone={r.status==='已通过'?'success':'neutral'}>{r.status}</Badge>}]
// Synthetic current-page response only. No ten-million-row allocation and no product API claim.
function response(q:Query):Row[]{return Array.from({length:20},(_,i)=>{const n=(q.page-1)*20+i+1;return{id:`BX-${String(n).padStart(5,'0')}`,name:['林亦','陈清','周予','许知'][i%4],reason:['项目差旅','办公用品','客户拜访','技术培训'][i%4],amount:q.sort?.key==='amount'?(q.sort.direction==='asc'?i*125+280:3200-i*125):[1280,560,2360,890][i%4],date:`2026-10-${String(7-i%7).padStart(2,'0')}`,status:i%3?'审批中':'已通过'}})}
export function DataWorkspaceDemo(){
 const [query,setQuery]=useState<Query>({page:1,sort:null}),[data,setData]=useState(()=>({query:{page:1,sort:null} as Query,rows:response({page:1,sort:null})})),[paused,setPaused]=useState(false),[pending,setPending]=useState(false),[stale,setStale]=useState(false),[hidden,setHidden]=useState<string[]>([]),[selected,setSelected]=useState<Set<string>>(new Set())
 useEffect(()=>{if(paused||!pending)return;const timer=setTimeout(()=>{setData({query,rows:response(query)});setPending(false);setSelected(new Set());setStale(false)},250);return()=>clearTimeout(timer)},[paused,pending,query])
 const request=(next:Query)=>{setQuery(next);setPending(true)}
 return <section aria-label="数据工作区" className="wo-data-workspace"><div className="wo-page-heading"><div><span className="wo-eyebrow">DATA WORKSPACE</span><h1>报销记录</h1></div><Badge>组件预览</Badge></div><div className="wo-table-toolbar"><span data-testid="table-selected">已选 {selected.size} 条</span><div><Button variant="ghost" aria-label="重新加载记录" disabled={pending} onClick={()=>request({...query,page:1})}><RefreshCw size={16}/></Button><MorphDialog><MorphDialogTrigger render={<Button variant="secondary"/>}><Columns3 size={15}/>显示字段</MorphDialogTrigger><MorphDialogContent><MorphDialogTitle className="wo-dialog-title">显示字段</MorphDialogTitle><MorphDialogDescription className="wo-dialog-description">仅调整显示，不改变筛选与排序</MorphDialogDescription><div className="wo-form">{columns.map(c=><Checkbox key={c.key} label={c.header} checked={!hidden.includes(c.key)} onCheckedChange={show=>setHidden(prev=>show?prev.filter(k=>k!==c.key):[...prev,c.key])}/>)}</div><div className="wo-dialog-footer"><MorphDialogClose render={<Button/>}>完成</MorphDialogClose></div></MorphDialogContent></MorphDialog></div></div><DataTable label="报销记录" rows={data.rows} columns={columns} rowKey={r=>r.id} hiddenColumns={hidden} sort={data.query.sort} onSortChange={sort=>request({page:1,sort})} selectedKeys={selected} onSelectionChange={setSelected} loading={pending} refreshRequired={stale} onRefresh={()=>request({...query,page:1})}/><Pagination page={data.query.page} pageSize={20} total={10_000_000} onPageChange={page=>request({...query,page})} disabled={pending||stale}/><details open className="wo-data-demo-controls"><summary>演示控制</summary><Checkbox label="暂停模拟响应" checked={paused} onCheckedChange={setPaused}/><Button variant="secondary" onClick={()=>setStale(true)}>模拟相关数据变化</Button><output data-testid="table-request">{JSON.stringify(query)}</output></details></section>
}
