import {useRef,useState} from 'react'
import type {ReactNode} from 'react'
import {Filter,Plus,Pencil,Trash2,ArrowLeft,X,Check} from 'lucide-react'
import {Button,Checkbox,Input,Select} from './primitives'
import {MorphDialog,MorphDialogTrigger,MorphDialogContent,MorphDialogTitle,MorphDialogDescription,MorphDialogClose} from './morph-dialog'
import {validateFilter} from './filter-model'
import type {FilterField,FilterPreset,FilterGroup,FilterCondition,FilterOperator} from './filter-model'
const labels:Record<FilterOperator,string>={eq:'等于',neq:'不等于',gt:'大于',gte:'大于或等于',lt:'小于',lte:'小于或等于'}
const condition=(fields:readonly FilterField[]):FilterCondition=>({fieldId:fields[0]?.id??'',operator:'eq',value:''})
function GroupEditor({value,onChange,fields,path='1',depth=1,disabled=false}:{value:FilterGroup;onChange:(group:FilterGroup)=>void;fields:readonly FilterField[];path?:string;depth?:number;disabled?:boolean}){
 const replace=(index:number,item:FilterCondition|FilterGroup)=>onChange({...value,children:value.children.map((child,i)=>i===index?item:child)})
 const add=(operator?:'and'|'or')=>onChange({...value,children:[...value.children,operator?{operator,children:[condition(fields)]}:condition(fields)]})
 return <fieldset className="wo-filter-group" disabled={disabled} aria-label={`${value.operator==='and'?'且':'或'}条件组 ${path}`}><legend><span>{value.operator==='and'?'且':'或'}</span><Select label={`匹配方式 ${path}`} value={value.operator} onValueChange={op=>onChange({...value,operator:op==='or'?'or':'and'})} disabled={disabled} options={[{value:'and',label:'满足全部条件'},{value:'or',label:'满足任一条件'}]}/></legend><div className="wo-filter-conditions">{value.children.map((child,index)=>{const childPath=`${path}.${index+1}`;return <div className="wo-filter-entry" key={childPath}>{'children' in child?<GroupEditor value={child} onChange={next=>replace(index,next)} fields={fields} depth={depth+1} path={childPath} disabled={disabled}/>:<div className="wo-filter-condition"><Select label={`字段 ${childPath}`} value={child.fieldId} disabled={disabled} options={fields.map(f=>({value:f.id,label:f.label}))} onValueChange={id=>replace(index,{fieldId:id??'',operator:'eq',value:''})}/><Select label={`比较方式 ${childPath}`} value={child.operator} disabled={disabled} options={(fields.find(f=>f.id===child.fieldId)?.type==='text'?['eq','neq']:['eq','neq','gt','gte','lt','lte']).map(op=>({value:op,label:labels[op as FilterOperator]}))} onValueChange={op=>replace(index,{...child,operator:op as FilterOperator})}/><Input aria-label={`条件值 ${childPath}`} value={child.value} disabled={disabled} placeholder="输入值" onChange={e=>replace(index,{...child,value:e.target.value})}/></div>}<Button variant="ghost" aria-label={`删除条件 ${childPath}`} disabled={disabled} onClick={()=>onChange({...value,children:value.children.filter((_,i)=>i!==index)})}><X size={14}/></Button></div>})}</div><div className="wo-filter-add"><Button variant="ghost" disabled={disabled} onClick={()=>add()} aria-label={`添加条件 ${path}`}><Plus size={13}/>条件</Button>{depth<3?<><Button variant="ghost" disabled={disabled} onClick={()=>add('and')} aria-label={`添加且条件组 ${path}`}><Plus size={13}/>且条件组</Button><Button variant="ghost" disabled={disabled} onClick={()=>add('or')} aria-label={`添加或条件组 ${path}`}><Plus size={13}/>或条件组</Button></>:null}</div></fieldset>
}
export interface FilterManagerProps{fields:readonly FilterField[];presets:readonly FilterPreset[];appliedId:string|null;onApply:(preset:FilterPreset|null)=>void;onSave:(preset:FilterPreset)=>Promise<void>;onDelete?:(id:string)=>Promise<void>;editorFooter?:ReactNode}
/** Host owns persisted presets and applied query. Saving never applies implicitly. */
export function FilterManager({fields,presets,appliedId,onApply,onSave,onDelete,editorFooter}:FilterManagerProps){
 const [open,setOpen]=useState(false),[draft,setDraft]=useState<FilterPreset|null>(null),[baseline,setBaseline]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[discard,setDiscard]=useState<'close'|'back'|null>(null),[remove,setRemove]=useState<FilterPreset|null>(null)
 const pending=useRef(false)
 const dirty=draft!==null&&JSON.stringify(draft)!==baseline
 function edit(preset?:FilterPreset){const next=preset?structuredClone(preset):{id:crypto.randomUUID(),name:'',filter:{operator:'and' as const,children:[condition(fields)]}};setDraft(next);setBaseline(JSON.stringify(next));setError('');setDiscard(null)}
 function back(){if(dirty){setDiscard('back');return}setDraft(null);setError('')}
 async function save(){
  if(pending.current||!draft)return
  const name=draft.name.trim(),issue=!name?'请输入筛选名称':name.length>80?'名称最多八十个字符':validateFilter(draft.filter,fields)
  if(issue){setError(issue);return}
  const next={...draft,name};if(new TextEncoder().encode(JSON.stringify(next)).length>32*1024){setError('筛选超过大小限制');return}
  pending.current=true;setBusy(true);setError('')
  try{await onSave(next);setDraft(null);setBaseline('')}catch(e){setError(e instanceof Error?e.message:'保存失败，请重试')}finally{pending.current=false;setBusy(false)}
 }
 async function deletePreset(){if(pending.current||!remove||!onDelete)return;pending.current=true;setBusy(true);setError('');try{await onDelete(remove.id);if(appliedId===remove.id)onApply(null);setRemove(null)}catch(e){setError(e instanceof Error?e.message:'删除失败，请重试')}finally{pending.current=false;setBusy(false)}}
 return <MorphDialog open={open} onOpenChange={(next,details)=>{if(pending.current){details.cancel();return}if(!next&&dirty){details.cancel();setDiscard('close');return}setOpen(next);if(next){setDraft(null);setError('');setRemove(null);setDiscard(null)}}}><MorphDialogTrigger render={<Button variant="secondary"/>}><Filter size={15}/>自定义筛选</MorphDialogTrigger><MorphDialogContent className="wo-filter-dialog"><MorphDialogTitle className="wo-dialog-title">{draft?'编辑筛选':'自定义筛选'}</MorphDialogTitle><MorphDialogDescription className="wo-dialog-description">{draft?'组合条件，保存后随时应用':'选择一个筛选应用到当前表格'}</MorphDialogDescription>
 {discard?<div className="wo-filter-confirm"><h3>放弃未保存的修改？</h3><div><Button variant="secondary" onClick={()=>setDiscard(null)}>继续编辑</Button><Button variant="danger" onClick={()=>{setDraft(null);setError('');if(discard==='close')setOpen(false);setDiscard(null)}}>放弃修改</Button></div></div>:remove?<div className="wo-filter-confirm"><h3>删除“{remove.name}”？</h3><div><Button variant="secondary" disabled={busy} onClick={()=>setRemove(null)}>取消</Button><Button variant="danger" busy={busy} onClick={()=>void deletePreset()}>确认删除</Button></div></div>:draft?<form className="wo-form" onSubmit={e=>{e.preventDefault();void save()}}><label className="wo-field"><span>筛选名称</span><Input aria-label="筛选名称" value={draft.name} maxLength={80} disabled={busy} placeholder="例如：本月待审批" onChange={e=>setDraft({...draft,name:e.target.value})}/></label><GroupEditor fields={fields} value={draft.filter} disabled={busy} onChange={filter=>setDraft({...draft,filter})}/>{editorFooter}<div className="wo-dialog-footer"><Button variant="ghost" disabled={busy} onClick={back}><ArrowLeft size={15}/>返回</Button><Button type="submit" busy={busy}>{busy?'正在保存':'保存筛选'}</Button></div></form>:<><div className="wo-filter-list">{presets.map(p=><div className="wo-filter-preset" key={p.id}><div><strong>{p.name}</strong><small>{p.filter.children.length} 项条件{appliedId===p.id?' · 使用中':''}</small></div><Button variant="ghost" aria-label={`编辑：${p.name}`} onClick={()=>edit(p)}><Pencil size={14}/></Button>{onDelete?<Button variant="ghost" aria-label={`删除：${p.name}`} onClick={()=>{setRemove(p);setError('')}}><Trash2 size={14}/></Button>:null}<Button variant={appliedId===p.id?'secondary':'ghost'} aria-label={`应用：${p.name}`} onClick={()=>{const issue=validateFilter(p.filter,fields);if(issue){setError(issue);return}onApply(p);setOpen(false)}}>{appliedId===p.id?<Check size={14}/>:null}应用</Button></div>)}{presets.length===0?<p>还没有保存的筛选</p>:null}</div><div className="wo-dialog-footer"><MorphDialogClose render={<Button variant="ghost"/>}>关闭</MorphDialogClose><Button disabled={!fields.length} onClick={()=>edit()}><Plus size={15}/>新建筛选</Button></div></>}
 {error?<p role="alert" className="wo-error wo-filter-error">{error}</p>:null}
 </MorphDialogContent></MorphDialog>
}
const demoFields:FilterField[]=[{id:'reason',label:'事由',type:'text'},{id:'amount',label:'金额',type:'number'},{id:'date',label:'申请日期',type:'time'},{id:'status',label:'状态',type:'text'}]
const demoPresets:FilterPreset[]=[{id:'pending',name:'待审批',filter:{operator:'and',children:[{fieldId:'status',operator:'eq',value:'审批中'}]}},{id:'large',name:'大额报销',filter:{operator:'and',children:[{fieldId:'amount',operator:'gte',value:'2000'}]}}]
export function FilterManagerDemo({onApply}:{onApply?:(preset:FilterPreset|null)=>void}){
 const [presets,setPresets]=useState(demoPresets),[applied,setApplied]=useState<FilterPreset|null>(null),[fail,setFail]=useState(false)
 return <div className="wo-filter-demo"><span data-testid="filter-applied">{applied?.name??'全部记录'}</span>{applied?<Button variant="ghost" aria-label="清除筛选" onClick={()=>{setApplied(null);onApply?.(null)}}><X size={14}/></Button>:null}<FilterManager fields={demoFields} presets={presets} appliedId={applied?.id??null} onApply={preset=>{setApplied(preset);onApply?.(preset)}} onSave={async next=>{await new Promise(resolve=>setTimeout(resolve,400));if(fail)throw new Error('模拟保存失败，请重试');setPresets(prev=>prev.some(p=>p.id===next.id)?prev.map(p=>p.id===next.id?next:p):[...prev,next])}} onDelete={async id=>{await new Promise(resolve=>setTimeout(resolve,250));setPresets(prev=>prev.filter(p=>p.id!==id))}} editorFooter={<Checkbox label="模拟筛选保存失败" checked={fail} onCheckedChange={setFail}/>}/><output data-testid="filter-saved" className="wo-sr-only">{JSON.stringify(presets)}</output></div>
}
