// User-authorized, original outline supplements. 24px grid, 1.6px rounded strokes.
// These are review artwork, not official Potlab assets. Existing originals are retained.
import React from 'react';
const revisions=import.meta.glob('../entries/potlab-icons/revisions/*.tsx',{eager:true,import:'default'});
const revised=Object.fromEntries(Object.entries(revisions).map(([path,value])=>[path.split('/').pop()!.replace('.tsx',''),value])) as Record<string,{body:string,accent:string,transform?:string,filled?:boolean}>;
const aliases:Record<string,string>={Undo2:'Undo2',Undo:'Undo2',Tick02Icon:'Check',Cancel01Icon:'Close',CheckIcon:'Check',ChevronsUpDown:'ChevronDown',ChevronDownIcon:'ChevronDown',ChevronUpIcon:'ChevronUp',ChevronLeftIcon:'ChevronLeft',ChevronRightIcon:'ChevronRight',X:'Close',XIcon:'Close',PlusIcon:'Plus',MinusIcon:'Minus',HomeIcon:'Home',FolderIcon:'Folder',CalendarDays:'Calendar',Calendar03Icon:'Calendar',IoCalendar:'Calendar',Ticket02Icon:'Ticket',Menu02Icon:'Menu',GripVertical:'Grip','missing:Grip':'Grip','missing:Cone':'Cone',BsPinFill:'Pin',BsFillPeopleFill:'Users',Building2:'Building',BriefcaseBusiness:'Briefcase',SaveIcon:'Save',Table2:'Table',CopyIcon:'Copy',ClipboardPaste:'Clipboard',FilePenLine:'FilePen',TextCursorInput:'TextCursor',GitBranch:'Branch',Maximize2:'Maximize',CircleStop:'Stop',ScrollText:'Scroll',TrendingDownIcon:'TrendingDown',FaUtensils:'Utensils',FaSailboat:'Boat',FaChargingStation:'Charging',FaPills:'Pills',IoFastFood:'Food',AlarmClockFreeIcons:'Alarm',PiFunnelSimpleBold:'Filter',BsCheckLg:'Check'};
export const reviewGlyphNames=["Undo2","Check","Minus","Plus","Close","ChevronDown","ChevronUp","ChevronLeft","ChevronRight","Circle","Paperclip","Calendar","Home","Folder","CornerDownLeft","Ticket","Menu","Pin","Users","Building","Briefcase","Save","Table","Copy","Clipboard","Scissors","FileCode","FilePen","ListChecks","AlignLeft","TextCursor","Hash","Calculator","Percent","Sigma","Heading","Branch","Maximize","ZoomIn","ZoomOut","Network","Scroll","Hand","Stop","Palette","Cone","TrendingDown","Utensils","Boat","Charging","Pills","Food","Alarm","Filter","Grip","MoreHorizontal","MoreVertical"];
export function glyphName(name:string){return revised[name]?name:aliases[name]||(revised[name.replace(/Icon$/, "")]?name.replace(/Icon$/, ""):null)}
export function ReviewGlyph({name,...props}:any){
 const key=glyphName(name),icon=key?revised[key]:undefined;
 if(!icon)return null;
 return <svg viewBox="0 0 24 24" fill="none" stroke="var(--potlab-ink,#0A0A30)" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" width="100%" height="100%" {...props}><g data-glyph-revision="V10" transform={icon.transform} strokeWidth={icon.filled?0:1.6}>{icon.body&&<path fill={icon.filled?"var(--potlab-ink,#0A0A30)":"none"} d={icon.body}/>}<path data-accent="true" fill={icon.filled?"var(--potlab-accent,#265BFF)":"none"} stroke="var(--potlab-accent,#265BFF)" d={icon.accent}/></g></svg>;
}
