import {test,expect} from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

test.beforeEach(async({page})=>{await page.goto('/weaveos.html');await page.getByRole('button',{name:'数据工作区',exact:true}).click()})
test('table renders only the current supplied page despite a large server total',async({page})=>{
 const table=page.getByRole('table',{name:'报销记录'});await expect(table).toBeVisible()
 await expect(table.getByRole('row')).toHaveCount(21)
 await expect(page.getByText('共 10,000,000 条',{exact:true})).toBeVisible()
 expect(await page.getByRole('navigation',{name:'表格分页'}).getByRole('button').count()).toBeLessThanOrEqual(10)
})
test('arbitrary page jump emits controlled request and waits for returned page',async({page})=>{
 await page.getByRole('checkbox',{name:'暂停模拟响应'}).check()
 await page.getByLabel('跳转页码').fill('321');await page.getByLabel('跳转页码').press('Enter')
 await expect(page.getByTestId('table-request')).toContainText('"page":321')
 await expect(page.getByText('当前第 1 页',{exact:true})).toBeVisible()
 await page.getByRole('checkbox',{name:'暂停模拟响应'}).uncheck()
 await expect(page.getByText('当前第 321 页',{exact:true})).toBeVisible()
})
test('text has no normal sort while numerical sorting is server-controlled',async({page})=>{
 await expect(page.getByRole('button',{name:'排序：事由'})).toHaveCount(0)
 await page.getByRole('checkbox',{name:'暂停模拟响应'}).check()
 const before=await page.getByRole('table',{name:'报销记录'}).getByRole('row').nth(1).innerText()
 await page.getByRole('button',{name:'排序：金额'}).click()
 await expect(page.getByTestId('table-request')).toContainText('"sort":{"key":"amount","direction":"asc"}')
 await expect(page.getByRole('table',{name:'报销记录'}).getByRole('row').nth(1)).toHaveText(before,{useInnerText:true})
})
test('hide a column changes display without clearing sort or issuing a query',async({page})=>{
 await page.getByRole('button',{name:'排序：金额'}).click()
 await expect(page.getByTestId('table-request')).toContainText('"key":"amount"')
 const request=await page.getByTestId('table-request').innerText()
 await page.getByRole('button',{name:'显示字段'}).click()
 const dialog=page.getByRole('dialog',{name:'显示字段'});await expect(dialog).toBeVisible()
 await dialog.getByRole('checkbox',{name:'金额',exact:true}).uncheck()
 await dialog.getByRole('button',{name:'完成',exact:true}).click();await expect(dialog).toBeHidden()
 await expect(page.getByRole('columnheader',{name:/金额/})).toHaveCount(0)
 await expect(page.getByTestId('table-request')).toHaveText(request)
})
test('related data change requires refresh and refresh requests page one',async({page})=>{
 await page.getByLabel('跳转页码').fill('8');await page.getByLabel('跳转页码').press('Enter');await expect(page.getByText('当前第 8 页',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'模拟相关数据变化'}).click()
 await expect(page.getByRole('alert')).toContainText('数据已更新')
 await expect(page.getByRole('button',{name:'下一页',exact:true})).toBeDisabled()
 await page.getByRole('button',{name:'刷新记录',exact:true}).click()
 await expect(page.getByText('当前第 1 页',{exact:true})).toBeVisible()
})
test('only current page selection is controlled and filtering does not happen locally',async({page})=>{
 await page.getByRole('checkbox',{name:'选择当前页记录'}).check()
 await expect(page.getByTestId('table-selected')).toHaveText('已选 20 条')
 await expect(page.getByRole('table',{name:'报销记录'}).getByRole('row')).toHaveCount(21)
})
test('table workspace passes settled accessibility and captures actual desktop UI',async({page})=>{
 await expect(page.getByRole('table',{name:'报销记录'})).toBeVisible()
 const scan=await new AxeBuilder({page}).include('[data-testid="workspace-card"]').analyze();expect(scan.violations).toEqual([])
 await page.screenshot({path:'test-results/weaveos-data-workspace.png',fullPage:false})
})
test('page-size change is a controlled request that resets to first page',async({page})=>{
 await page.getByLabel('跳转页码').fill('8');await page.getByLabel('跳转页码').press('Enter');await expect(page.getByText('当前第 8 页',{exact:true})).toBeVisible()
 await page.getByRole('combobox',{name:'每页行数'}).click();await page.getByRole('option',{name:'10 条 / 页',exact:true}).click()
 await expect(page.getByTestId('table-request')).toContainText('"pageSize":10')
 await expect(page.getByText('当前第 1 页',{exact:true})).toBeVisible()
 await expect(page.getByRole('table',{name:'报销记录'}).getByRole('row')).toHaveCount(11)
})
test('invalid arbitrary page never emits a coerced query',async({page})=>{
 const before=await page.getByTestId('table-request').innerText()
 await page.getByLabel('跳转页码').fill('1.5');await page.getByLabel('跳转页码').press('Enter')
 await expect(page.getByRole('alert')).toContainText('整数')
 await expect(page.getByTestId('table-request')).toHaveText(before)
})
test('failed response keeps previous confirmed page and exposes an explicit retry',async({page})=>{
 await page.getByRole('checkbox',{name:'模拟查询失败'}).check()
 await page.getByRole('button',{name:'下一页',exact:true}).click()
 await expect(page.getByRole('alert')).toContainText('模拟查询失败')
 await expect(page.getByText('当前第 1 页',{exact:true})).toBeVisible()
 await page.getByRole('checkbox',{name:'模拟查询失败'}).uncheck();await page.getByRole('button',{name:'重试',exact:true}).click()
 await expect(page.getByRole('alert')).toHaveCount(0)
 await expect(page.getByText('当前第 2 页',{exact:true})).toBeVisible()
 await expect(page.getByRole('table',{name:'报销记录'}).getByRole('row')).toHaveCount(21)
})
