import {test,expect} from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
test.beforeEach(async({page})=>{await page.goto('/weaveos.html');await page.getByRole('button',{name:'数据工作区',exact:true}).click();await page.getByRole('button',{name:'自定义筛选',exact:true}).click()})
test('opens saved-filter management first, with only one preset applied',async({page})=>{
 const dialog=page.getByRole('dialog',{name:'自定义筛选'});await expect(dialog).toBeVisible()
 await expect(dialog).toHaveCSS('opacity','1');await page.screenshot({path:'test-results/weaveos-filter-manager.png'})
 await dialog.getByRole('button',{name:'应用：待审批'}).click()
 await expect(page.getByTestId('filter-applied')).toHaveText('待审批')
 await page.getByRole('button',{name:'自定义筛选',exact:true}).click()
 await dialog.getByRole('button',{name:'应用：大额报销'}).click()
 await expect(page.getByTestId('filter-applied')).toHaveText('大额报销')
 await page.getByRole('button',{name:'清除筛选'}).click();await expect(page.getByTestId('filter-applied')).toHaveText('全部记录')
})
test('constructs AND with an OR subgroup and persists exact conditions',async({page})=>{
 const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'新建筛选'}).click()
 await dialog.getByLabel('筛选名称').fill('财务检查')
 await dialog.getByLabel('条件值 1.1',{exact:true}).fill('差旅')
 await dialog.getByRole('button',{name:'添加或条件组 1',exact:true}).click()
 await expect(dialog.getByRole('group',{name:'或条件组 1.2',exact:true})).toBeVisible()
 await dialog.getByLabel('条件值 1.2.1',{exact:true}).fill('客户')
 await page.screenshot({path:'test-results/weaveos-filter-nested.png'})
 await dialog.getByRole('button',{name:'保存筛选',exact:true}).click()
 await expect(dialog.getByRole('button',{name:'应用：财务检查'})).toBeVisible()
 const saved=JSON.parse(await page.getByTestId('filter-saved').innerText()).find((preset:{name:string})=>preset.name==='财务检查')
 expect(saved).toEqual({id:expect.any(String),name:'财务检查',filter:{operator:'and',children:[{fieldId:'reason',operator:'eq',value:'差旅'},{operator:'or',children:[{fieldId:'reason',operator:'eq',value:'客户'}]}]}})
})
test('failed persistence retains editor and never reports saved',async({page})=>{
 await page.getByRole('dialog').getByRole('button',{name:'新建筛选'}).click()
 await page.getByLabel('筛选名称').fill('失败不丢失')
 await page.getByRole('checkbox',{name:'模拟筛选保存失败'}).check()
 await page.getByRole('button',{name:'保存筛选',exact:true}).click()
 await expect(page.getByRole('alert')).toContainText('模拟保存失败')
 await expect(page.getByLabel('筛选名称')).toHaveValue('失败不丢失')
 await expect(page.getByTestId('filter-saved')).not.toContainText('失败不丢失')
})
test('dirty Escape asks before discarding and restores source focus',async({page})=>{
 await page.getByRole('button',{name:'新建筛选'}).click();await page.getByLabel('筛选名称').fill('未保存')
 await page.keyboard.press('Escape')
 const dialog=page.getByRole('dialog');await expect(dialog.getByText('放弃未保存的修改？')).toBeVisible()
 await dialog.getByRole('button',{name:'继续编辑'}).click();await expect(page.getByLabel('筛选名称')).toHaveValue('未保存')
 await page.keyboard.press('Escape');await dialog.getByRole('button',{name:'放弃修改'}).click();await expect(dialog).toBeHidden()
 await expect(page.getByRole('button',{name:'自定义筛选',exact:true})).toBeFocused()
})
test('text comparisons exclude range operators and editor is accessible',async({page})=>{
 await page.getByRole('button',{name:'新建筛选'}).click()
 await page.getByRole('combobox',{name:'比较方式 1.1'}).click()
 await expect(page.getByRole('option')).toHaveText(['等于','不等于'])
 await page.keyboard.press('Escape')
 const scan=await new AxeBuilder({page}).include('[role="dialog"]').analyze();expect(scan.violations).toEqual([])
 await page.screenshot({path:'test-results/weaveos-filter-editor.png',fullPage:false})
})
test('applying a preset emits a page-one host query without client-side table filtering',async({page})=>{
 await page.getByRole('button',{name:'应用：待审批'}).click()
 await expect.poll(async()=>JSON.parse(await page.getByTestId('table-request').innerText())).toEqual({page:1,sort:null,filter:{operator:'and',children:[{fieldId:'status',operator:'eq',value:'审批中'}]}})
})
test('editing a saved preset preserves identity, saving alone does not apply',async({page})=>{
 await page.getByRole('button',{name:'编辑：待审批'}).click();await expect(page.getByLabel('筛选名称')).toHaveValue('待审批')
 await page.getByLabel('筛选名称').fill('我的待办');await page.getByRole('button',{name:'保存筛选',exact:true}).click()
 await expect(page.getByRole('button',{name:'应用：我的待办'})).toBeVisible()
 await expect(page.getByRole('button',{name:'应用：待审批'})).toHaveCount(0)
 await expect(page.getByTestId('filter-applied')).toHaveText('全部记录')
})
test('deleting a preset requires confirmation and cancellation preserves it',async({page})=>{
 await page.getByRole('button',{name:'删除：待审批'}).click();await page.getByRole('button',{name:'取消',exact:true}).click()
 await expect(page.getByRole('button',{name:'应用：待审批'})).toBeVisible()
 await page.getByRole('button',{name:'删除：待审批'}).click();await page.getByRole('button',{name:'确认删除'}).click()
 await expect(page.getByRole('button',{name:'应用：待审批'})).toHaveCount(0)
})
