import {FieldSelect,Input} from "@/shared/ui";
import {Checkbox} from "@/components/motion/checkbox";
import type {LowcodeField} from "./field-model";
import {phoneTypes,textPresets,subtablePolicy,type AdvancedFieldConfig} from "./advanced-fields";
export function AdvancedFieldSettings({field,onChange,disabled}:{field:LowcodeField;onChange:(patch:Partial<LowcodeField>)=>void;disabled:boolean}){
  const config=field.advancedConfig??{},change=(patch:Partial<AdvancedFieldConfig>)=>onChange({advancedConfig:{...config,...patch}});
  return <fieldset disabled={disabled} className="space-y-4">
    {["text","textarea","email","phone","url"].includes(field.type)&&<section className="space-y-3 border-t border-border pt-4"><h3 className="text-caption font-semibold text-muted-foreground">输入与格式</h3><FieldSelect label="移动端键盘" value={config.inputMode??(field.type==="phone"?"tel":field.type==="email"?"email":field.type==="url"?"url":"text")} options={[{value:"text",label:"文本键盘"},{value:"numeric",label:"数字键盘"},{value:"decimal",label:"小数键盘"},{value:"tel",label:"电话键盘"},{value:"email",label:"邮箱键盘"},{value:"url",label:"网址键盘"},{value:"search",label:"搜索键盘"}]} onChange={inputMode=>change({inputMode:inputMode as AdvancedFieldConfig["inputMode"]})}/><p className="text-caption leading-5 text-muted-foreground">键盘是浏览器输入提示；保存格式由下方预设和字段类型校验。</p>{field.type==="text"&&<FieldSelect label="限定文本格式" value={config.textPreset??"none"} options={Object.entries(textPresets).map(([value,label])=>({value,label}))} onChange={textPreset=>change({textPreset:textPreset as AdvancedFieldConfig["textPreset"]})}/>} {field.type==="phone"&&<><FieldSelect label="电话类型" value={config.phoneType??"any"} options={Object.entries(phoneTypes).map(([value,label])=>({value,label}))} onChange={phoneType=>change({phoneType:phoneType as AdvancedFieldConfig["phoneType"]})}/><p className="text-caption text-muted-foreground">固定电话包含区号，可使用短横线分隔分机；国际号码使用 + 和 7 至 15 位数字。</p></>}</section>}
    {field.type==="divider"&&<section className="space-y-3 border-t border-border pt-4"><h3 className="text-caption font-semibold text-muted-foreground">分隔线外观</h3><FieldSelect label="线条样式" value={config.divider?.style??"solid"} options={[{value:"solid",label:"实线"},{value:"dashed",label:"虚线"},{value:"dotted",label:"点线"},{value:"double",label:"双线"}]} onChange={style=>change({divider:{...config.divider,style:style as NonNullable<AdvancedFieldConfig["divider"]>["style"]}})}/><Input label="线条粗细（像素）" type="number" min={1} max={8} step={1} value={String(config.divider?.thickness??1)} onChange={value=>change({divider:{...config.divider,thickness:Number(value)}})}/></section>}
    {field.type==="subtable"&&<section className="space-y-3 border-t border-border pt-4"><h3 className="text-caption font-semibold text-muted-foreground">明细行操作</h3><FieldSelect label="行间距" value={subtablePolicy(field).density} options={[{value:"comfortable",label:"宽松"},{value:"compact",label:"紧凑"}]} onChange={density=>change({subtable:{...config.subtable,density:density as "comfortable"|"compact"}})}/>{(["allowAdd","allowDelete","allowCopy"] as const).map(key=><Checkbox key={key} label={{allowAdd:"允许新增行",allowDelete:"允许删除行",allowCopy:"允许复制行及批量复制"}[key]} checked={subtablePolicy(field)[key]} onCheckedChange={checked=>change({subtable:{...config.subtable,[key]:checked}})}/>)}<p className="text-caption leading-5 text-muted-foreground">增删限制同时在保存时校验；禁止新增时，新记录的子表从空列表开始。复制会产生新行 ID，计算、只读字段和签名重新填写或计算。</p></section>}
    {["image","attachment","displayImage"].includes(field.type)&&<section className="space-y-3 border-t border-border pt-4"><h3 className="text-caption font-semibold text-muted-foreground">文件入口</h3>{field.type!=="attachment"&&<><FieldSelect label="图片选择来源" value={config.media?.capture??"any"} options={[{value:"any",label:"文件或相册"},{value:"camera",label:"优先使用相机拍摄"}]} onChange={capture=>change({media:{...config.media,capture:capture as "any"|"camera"}})}/><Checkbox label="显示桌面设备上传入口" checked={config.media?.allowDesktopUpload!==false} onCheckedChange={allowDesktopUpload=>change({media:{...config.media,allowDesktopUpload}})}/><p className="text-caption leading-5 text-muted-foreground">相机提示和触控设备识别由浏览器提供，不能证明文件拍摄来源或替代访问权限。</p></>}<Checkbox label="显示预览入口" checked={config.media?.preview!==false} onCheckedChange={preview=>change({media:{...config.media,preview}})}/><Checkbox label="显示下载按钮" checked={config.media?.download!==false} onCheckedChange={download=>change({media:{...config.media,download}})}/><p className="text-caption leading-5 text-muted-foreground">入口开关只影响此表单中的按钮；文件读取仍使用原记录权限。</p></section>}
  </fieldset>;
}
