import { ActionSurface } from "@/components/controls";
import {AutomationPrintArtifacts} from "./AutomationPrintArtifacts";
import {useEffect,useState} from "react";
import {api} from "@/shared/api/client";
import {Button} from "@/shared/ui";
import {base,dateLabel,message,useLoad} from "./model";
import {automationKinds,normalizeAutomationRun,redactAutomationValue,runStates,type AutomationKind,type AutomationRun,type AutomationRunResponse} from "./automation-model";
export function AutomationRunDetail({id,onRetried,manager=false}:{id:string;onRetried?:()=>void;manager?:boolean}) {
  const run=useLoad<AutomationRunResponse>(`${base}/automation-runs/${id}`),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{if(!run.data||!["QUEUED","PENDING","RUNNING","RETRY","RETRYING"].includes(run.data.run.state??run.data.run.status))return;const timer=setTimeout(run.refresh,3000);return()=>clearTimeout(timer);},[run.data]);
  async function retry(){setBusy(true);setError("");try{await api(`${base}/automation-runs/${id}/retry`,"POST",{});run.refresh();onRetried?.();}catch(e){setError(message(e));}finally{setBusy(false);}}
  if(!run.data)return <div className="space-y-3"><p className="text-body text-muted-foreground">{run.error||"正在读取运行详情…"}</p><Button size="sm" variant="ghost" onClick={run.refresh}>重新读取</Button></div>;
  const value=normalizeAutomationRun(run.data);
  return <section className="min-w-0 space-y-4"><header className="flex flex-wrap items-center gap-3"><h3 className="text-body font-medium">运行详情 · {runStates[value.status]??value.status}</h3><Button size="sm" variant="ghost" onClick={run.refresh}>刷新运行</Button>{["FAILED","RETRY"].includes(value.status)&&(value.canRetry??manager)&&value.retryable!==false&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>void retry()}>{busy?"正在请求…":"重试失败运行"}</Button>}</header><p className="text-caption text-muted-foreground">创建于 {dateLabel(value.createdAt)} · 尝试 {value.attempt??value.attempts??1} 次</p>{(value.errorCode||value.error)&&<p role="alert" className="whitespace-pre-wrap rounded-control bg-destructive/5 p-3 text-body text-destructive">{value.errorCode}{value.errorCode&&value.error?" · ":""}{value.error}</p>}{error&&<p role="alert" className="text-body text-destructive">{error}</p>}<AutomationPrintArtifacts artifacts={value.artifacts??[]}/><ol className="space-y-3">{(value.steps??[]).map((step,index)=><li key={step.id??`${step.stepPath??step.stepId}-${index}`} className="rounded-card border border-border p-3"><div className="flex flex-wrap gap-2 text-body"><span>{step.stepPath??step.stepId??index+1}</span><span>{automationKinds[step.kind as AutomationKind]??step.kind}</span><span>{runStates[step.status]??step.status}</span></div>{step.startedAt&&<p className="mt-2 text-caption text-muted-foreground">{dateLabel(step.startedAt)} → {dateLabel(step.finishedAt)}</p>}{(step.error||step.errorCode)&&<p role="alert" className="mt-2 whitespace-pre-wrap text-caption text-destructive">{step.errorCode} {step.error}</p>}{step.output!==undefined&&<details className="mt-3"><summary className="cursor-pointer text-caption text-muted-foreground">查看已脱敏输出</summary><pre className="mt-2 max-h-64 overflow-auto whitespace-pre-wrap break-words rounded-control bg-muted/30 p-3 text-caption">{JSON.stringify(redactAutomationValue(step.output),null,2)}</pre></details>}</li>)}</ol>{!value.steps?.length&&<p className="text-caption text-muted-foreground">当前尚无步骤执行记录。</p>}</section>;
}
export function AutomationRuns({automationId,initialRunId}:{automationId:string;initialRunId?:string}) {
  const runs=useLoad<AutomationRun[]>(`${base}/automations/${automationId}/runs`),[selected,setSelected]=useState(initialRunId);
  useEffect(()=>{setSelected(initialRunId);runs.refresh();},[automationId,initialRunId]);
  return <div className="grid min-w-0 gap-5 lg:grid-cols-application-settings"><section className="space-y-3"><div className="flex items-center gap-2"><h3 className="flex-1 text-body font-medium">运行记录</h3><Button size="sm" variant="ghost" onClick={runs.refresh}>刷新</Button></div>{runs.error&&<p role="alert" className="text-body text-destructive">{runs.error}</p>}{runs.loading?<p className="text-caption text-muted-foreground">正在加载…</p>:!runs.data?.length?<p className="text-caption text-muted-foreground">尚无运行记录。</p>:runs.data.map(run=><ActionSurface active={selected===run.id} type="button" key={run.id} className="block w-full text-left" onClick={()=>setSelected(run.id)}><span>{runStates[run.state??run.status]??run.state??run.status}</span><time className="mt-1 block text-caption text-muted-foreground">{dateLabel(run.createdAt)}</time></ActionSurface>)}</section>{selected?<AutomationRunDetail id={selected} manager onRetried={runs.refresh}/>:<p className="text-body text-muted-foreground">选择一条运行记录查看每步结果。</p>}</div>;
}
