import {AutomationPrintSettings} from "./AutomationPrintSettings";
import {useState} from "react";
import {Button,FieldSelect,Input} from "@/shared/ui";
import type {Directory} from "../organization/model";
import {isDecoration,type TableSchema} from "./field-model";
import {computedField} from "./calculations";
import {RuleEditor} from "./RuleEditor";
import {CalculationEditor} from "./CalculationEditor";
import {AutomationBindingEditor,AutomationMappingEditor} from "./AutomationBindings";
import {automationKinds,externalKinds,inputFields,moveAutomationStep,newAutomationStep,stepCount,type Automation,type AutomationConnector,type AutomationKind,type AutomationStep} from "./automation-model";
import type {RelationTable} from "./relations";
const hints:Record<AutomationKind,string>={PRINT:"使用已发布命名模板生成 DOCX，不调用打印机。仅读取匹配版本的正式记录，生成后保存原修订快照。",ORG_QUERY:"读取当前启用并绑定门户的成员；可输出匹配成员的直属上级或最近部门负责人。输出 userIds 可直接用于通知，items 含主部门、岗位和有效负责人关系。",QUERY:"读取有权限的目标记录，最多五十条。输出 items 可供循环使用。",CREATE:"向目标表提交新增；表中的字段校验、权限及审批仍生效。",UPDATE:"使用记录 ID 和当前内容版本更新。提交后按目标表审批规则处理。",DELETE:"删除指定记录，需要记录 ID、内容版本和目标表删除权限。",CONDITION:"条件针对触发记录字段判断；可选 inputs.data 替换比较数据。",FOREACH:"对 items 列表逐项执行，item 表示当前项，最多五十项。",SUBFLOW:"调用已发布的子自动化；服务端检查权限和递归深度。",FUNCTION:"为变量映射数值，再组合加减乘除；结果可被后续步骤引用。",NOTICE:"发送站内通知，需要接收用户 ID 列表和消息内容。",HTTP:"使用管理员配置的地址与凭据引用；运行结果中敏感内容会隐藏。",AI:"使用服务端已配置的模型服务；未配置时显示失败，不产生模拟结果。",EMAIL:"通过受信连接器发送邮件，需要接收人、主题和正文。",SMS:"通过受信连接器发送短信，需要接收号码和消息内容。"};
const inputKeys:Record<AutomationKind,{value:string;label:string}[]>={PRINT:[{value:"recordId",label:"正式记录 ID"},{value:"revision",label:"内容修订"}],ORG_QUERY:[{value:"departmentIds",label:"部门或小组 ID 列表"},{value:"positionIds",label:"岗位 ID 列表"},{value:"userIds",label:"成员 ID 列表"},{value:"limit",label:"最多人数（1～50）"}],QUERY:[{value:"query",label:"搜索文字"},{value:"limit",label:"最多条数（1～50）"}],CREATE:[{value:"title",label:"记录标题"},{value:"data",label:"完整字段对象"}],UPDATE:[{value:"recordId",label:"目标记录 ID"},{value:"revision",label:"内容版本"},{value:"title",label:"记录标题"},{value:"data",label:"完整字段对象"}],DELETE:[{value:"recordId",label:"目标记录 ID"},{value:"revision",label:"内容版本"}],CONDITION:[{value:"data",label:"条件数据对象（可选）"}],FOREACH:[{value:"items",label:"需要循环的列表"}],SUBFLOW:[{value:"data",label:"传入子自动化的数据"}],FUNCTION:[],NOTICE:[{value:"recipients",label:"接收用户 ID 列表"},{value:"message",label:"通知内容"}],HTTP:[{value:"body",label:"请求内容"}],AI:[{value:"prompt",label:"处理提示"},{value:"chunks",label:"上下文文本列表（可选）"}],EMAIL:[{value:"to",label:"接收邮箱"},{value:"subject",label:"邮件主题"},{value:"body",label:"邮件正文"}],SMS:[{value:"to",label:"接收号码"},{value:"message",label:"短信内容"}]};
type Props={steps:AutomationStep[];onChange:(steps:AutomationStep[])=>void;rootSteps:AutomationStep[];schema:TableSchema;directory:Directory;tables:RelationTable[];automations:Automation[];connectors:AutomationConnector[];disabled?:boolean;depth?:number;previous?:AutomationStep[]};
export function AutomationStepEditor({steps,onChange,rootSteps,schema,directory,tables,automations,connectors,disabled,depth=1,previous=[]}:Props) {
  const [kind,setKind]=useState<AutomationKind>("QUERY"),fields=schema.fields.filter(field=>!isDecoration(field));
  function update(index:number,patch:Partial<AutomationStep>){onChange(steps.map((step,at)=>at===index?{...step,...patch}:step));}
  function contents(step:AutomationStep,index:number){const earlier=[...previous,...steps.slice(0,index)],target=tables.find(table=>table.id.toLowerCase()===step.tableId?.toLowerCase()),writable=target?.fields.filter(field=>!isDecoration(field)&&!computedField(field)&&!field.readOnly&&field.type!=="serial");
    const binding=(key:string,label:string,fallback={literal:""} as {literal:unknown}|{path:string})=><AutomationBindingEditor key={key} label={label} value={step.inputs?.[key]??fallback} onChange={value=>update(index,{inputs:{...step.inputs,[key]:value}})} fields={fields} availableSteps={earlier} disabled={disabled}/>;
    return <div className="space-y-4"><Input label="步骤标识（自动生成）" value={step.id} readOnly/><p className="text-caption leading-5 text-muted-foreground">{hints[step.kind]}</p>
      {["QUERY","PRINT","CREATE","UPDATE","DELETE"].includes(step.kind)&&<FieldSelect label="目标数据表" value={step.tableId??""} options={tables.map(table=>({value:table.id,label:`${table.appName} · ${table.name}`}))} onChange={tableId=>update(index,{tableId,values:undefined,...(step.kind==="PRINT"?{printTemplateId:undefined}:{})})}/>}
      {step.kind==="ORG_QUERY"&&<>{step.inputs?.selection&&"path" in step.inputs.selection?binding("selection","返回人员类型"): <FieldSelect label="返回人员" value={step.inputs?.selection&&"literal" in step.inputs.selection?String(step.inputs.selection.literal):"MEMBERS"} options={[{value:"MEMBERS",label:"匹配成员"},{value:"DIRECT_MANAGERS",label:"匹配成员的直属上级"},{value:"DEPARTMENT_LEADERS",label:"匹配成员的部门负责人"}]} onChange={selection=>update(index,{inputs:{...step.inputs,selection:{literal:selection}}})}/>} {step.inputs?.includeDescendants&&"path" in step.inputs.includeDescendants?binding("includeDescendants","包含下级组织"): <FieldSelect label="部门筛选范围" value={step.inputs?.includeDescendants&&"literal" in step.inputs.includeDescendants?String(step.inputs.includeDescendants.literal):"true"} options={[{value:"true",label:"包含下级组织"},{value:"false",label:"仅直接所属组织"}]} onChange={value=>update(index,{inputs:{...step.inputs,includeDescendants:{literal:value==="true"}}})}/>}<p className="text-caption leading-5 text-muted-foreground">不同筛选取交集，同一列表内取并集。省略列表表示不限制；空列表表示没有匹配成员。固定列表使用 JSON 数组，或绑定部门、岗位、成员字段。最多返回 50 人，超出时 hasMore 为 true。</p></>}
      {step.kind==="PRINT"&&<AutomationPrintSettings tableId={step.tableId} templateId={step.printTemplateId} onChange={printTemplateId=>update(index,{printTemplateId})} disabled={disabled}/>}
      {step.kind==="SUBFLOW"&&<><FieldSelect label="已有自动化" value={step.automationId??""} options={automations.filter(automation=>automation.publishedVersionId||automation.publishedVersion).map(automation=>({value:automation.id,label:automation.name}))} onChange={automationId=>update(index,{automationId})}/><Input label="子自动化 ID" value={step.automationId??""} placeholder="选择上方定义，或填写有权调用的自动化 ID" onChange={automationId=>update(index,{automationId})}/></>}
      {externalKinds.has(step.kind)&&<><FieldSelect label="已配置连接器" value={step.connectorId??""} options={connectors.map(connector=>({value:connector.id,label:`${connector.name}${connector.enabled?"":" · 已停用"}`}))} onChange={connectorId=>update(index,{connectorId})}/>{!connectors.length&&<p role="status" className="rounded-control bg-status-warning/10 p-3 text-caption text-status-warning">请先在连接器管理中保存受信地址和环境变量凭据引用。</p>}</>}
      {step.kind==="FOREACH"&&binding("items","循环列表",{path:earlier.length?`steps.${earlier.at(-1)!.id}.items`:"trigger.data.items"})}
      {step.kind==="CONDITION"&&<RuleEditor value={step.rule??{fieldId:fields[0]?.id??"",operator:"NOT_EMPTY"}} onChange={rule=>update(index,{rule})} fields={fields} directory={directory} disabled={disabled}/>}
      {step.kind==="FUNCTION"?<><AutomationMappingEditor numeric label="数值变量" value={step.values} onChange={values=>update(index,{values})} fields={fields} availableSteps={earlier} disabled={disabled}/><CalculationEditor allowedResultTypes={["number"]} field={{id:"calculation",label:"计算",type:"formula",formulaConfig:{expression:step.formula??{op:"CONST",value:0}}}} fields={inputFields(step.values).map(field=>({...field,type:"number" as const}))} disabled={!!disabled} onChange={patch=>update(index,{formula:patch.formulaConfig?.expression})}/></>:step.kind!=="FOREACH"&&<AutomationMappingEditor label={externalKinds.has(step.kind)?"请求字段":"输入参数"} allowCustom={externalKinds.has(step.kind)} maxEntries={externalKinds.has(step.kind)?100:50} value={externalKinds.has(step.kind)?step.values:step.kind==="ORG_QUERY"?Object.fromEntries(Object.entries(step.inputs??{}).filter(([key])=>!["selection","includeDescendants"].includes(key))):step.inputs} onChange={inputs=>update(index,externalKinds.has(step.kind)?{values:inputs}:{inputs:step.kind==="ORG_QUERY"?{...(step.inputs?.selection?{selection:step.inputs.selection}:{}),...(step.inputs?.includeDescendants?{includeDescendants:step.inputs.includeDescendants}:{}),...inputs}:inputs,...(["CREATE","UPDATE"].includes(step.kind)&&inputs.data?{values:undefined}:{})})} fields={fields} availableSteps={earlier} disabled={disabled} knownKeys={inputKeys[step.kind].filter(key=>step.kind!=="FOREACH"||key.value!=="items")}/>}
      {["CREATE","UPDATE"].includes(step.kind)&&<AutomationMappingEditor maxEntries={100} label="写入字段" value={step.values} onChange={values=>update(index,{values})} fields={fields} targetFields={writable??[]} availableSteps={earlier} disabled={disabled||!!step.inputs?.data}/>}
      {["CONDITION","FOREACH"].includes(step.kind)&&<div className="space-y-4 border-l-2 border-primary/30 pl-3"><h4 className="text-body font-medium">{step.kind==="CONDITION"?"条件满足时":"每项执行"}</h4><AutomationStepEditor steps={step.steps??[]} onChange={children=>update(index,{steps:children})} rootSteps={rootSteps} schema={schema} directory={directory} tables={tables} automations={automations} connectors={connectors} disabled={disabled} depth={depth+1} previous={earlier}/>{step.kind==="CONDITION"&&<><h4 className="text-body font-medium">条件不满足时</h4><AutomationStepEditor steps={step.elseSteps??[]} onChange={elseSteps=>update(index,{elseSteps})} rootSteps={rootSteps} schema={schema} directory={directory} tables={tables} automations={automations} connectors={connectors} disabled={disabled} depth={depth+1} previous={earlier}/></>}</div>}
    </div>;
  }
  return <fieldset disabled={disabled} className="min-w-0 space-y-3">{steps.map((step,index)=><details key={step.id} open className="min-w-0 rounded-card border border-border bg-card p-4"><summary className="cursor-pointer text-body font-medium">{index+1}. {automationKinds[step.kind]} · {step.id}</summary><div className="my-3 flex flex-wrap justify-end gap-1"><Button size="sm" variant="ghost" aria-label={`上移步骤 ${step.id}`} disabled={disabled||index===0} onClick={()=>onChange(moveAutomationStep(steps,index,-1))}>上移</Button><Button size="sm" variant="ghost" aria-label={`下移步骤 ${step.id}`} disabled={disabled||index===steps.length-1} onClick={()=>onChange(moveAutomationStep(steps,index,1))}>下移</Button><Button size="sm" variant="ghost" aria-label={`删除步骤 ${step.id}`} onClick={()=>onChange(steps.filter((_,at)=>at!==index))}>删除</Button></div>{contents(step,index)}</details>)}{depth<=5&&<div className="flex flex-wrap items-end gap-2 rounded-card border border-dashed border-border p-3"><div className="min-w-40 flex-1"><FieldSelect label={depth===1?"添加步骤类型":"添加内部步骤类型"} value={kind} options={(Object.keys(automationKinds) as AutomationKind[]).filter(kind=>depth<5||!["CONDITION","FOREACH"].includes(kind)).map(value=>({value,label:automationKinds[value]}))} onChange={value=>setKind(value as AutomationKind)}/></div><Button variant="outline" size="sm" disabled={disabled||stepCount(rootSteps)>=50} onClick={()=>{const step=newAutomationStep(kind,rootSteps);if(kind==="PRINT")step.inputs={recordId:{path:"trigger.recordId"},revision:{path:"trigger.revision"}};if(kind==="CONDITION")step.rule={fieldId:fields[0]?.id??"",operator:"NOT_EMPTY"};if(kind==="FOREACH")step.inputs={items:{path:steps.length?`steps.${steps.at(-1)!.id}.items`:previous.length?`steps.${previous.at(-1)!.id}.items`:"trigger.data.items"}};onChange([...steps,step]);}}>添加步骤</Button></div>}</fieldset>;
}
