import { ActionSurface } from "@/components/controls";
import {useState} from "react";
import {api} from "@/shared/api/client";
import {AppModal,Button,FieldSelect,Input} from "@/shared/ui";
import {Checkbox} from "@/components/motion/checkbox";
import {base,message} from "./model";
import {connectorError,type AutomationConnector} from "./automation-model";
export function AutomationConnectors({appId,connectors,onSaved,onClose}:{appId:string;connectors:AutomationConnector[];onSaved:()=>void;onClose:()=>void}) {
  const [selected,setSelected]=useState<AutomationConnector>(),[name,setName]=useState(""),[url,setUrl]=useState(""),[method,setMethod]=useState<AutomationConnector["method"]>("POST"),[enabled,setEnabled]=useState(true),[authorizationEnv,setAuthorizationEnv]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  function choose(connector?:AutomationConnector){setSelected(connector);setName(connector?.name??"");setUrl(connector?.url??"");setMethod(connector?.method??"POST");setEnabled(connector?.enabled??true);setAuthorizationEnv(connector?.authorizationEnv??"");setError("");}
  async function save(){const input={name,url,method,enabled,...(authorizationEnv?{authorizationEnv}:{})},validation=connectorError(input);if(validation){setError(validation);return;}setBusy(true);setError("");try {const result=await api<AutomationConnector>(selected?`${base}/automation-connectors/${selected.id}`:`${base}/applications/${appId}/automation-connectors`,selected?"PUT":"POST",{...input,...(selected?{revision:selected.revision}:{})});choose(result);onSaved();}catch(e){setError(message(e));}finally{setBusy(false);}}
  return <AppModal open onOpenChange={open=>{if(!open&&!busy)onClose();}} title="自动化连接器" description="仅应用管理者可配置。地址必须通过服务端的主机许可列表；凭据使用服务器环境变量引用。" className="max-w-4xl" dismissible={!busy} footer={<Button disabled={busy} onClick={()=>void save()}>{busy?"正在保存…":selected?"保存连接器":"创建连接器"}</Button>}><div className="grid gap-5 md:grid-cols-connector-settings"><nav aria-label="连接器列表" className="space-y-2"><Button size="sm" variant="outline" disabled={busy} onClick={()=>choose()}>新建连接器</Button>{connectors.map(connector=><ActionSurface active={selected?.id===connector.id} key={connector.id} type="button" disabled={busy} className="block w-full text-left" onClick={()=>choose(connector)}>{connector.name}<span className="mt-1 block text-caption text-muted-foreground">{connector.method} · {connector.enabled?"已启用":"已停用"}</span></ActionSurface>)}</nav><fieldset disabled={busy} className="space-y-4"><Input label="连接器名称" value={name} maxLength={128} onChange={setName}/><Input label="请求地址" value={url} placeholder="https://trusted-service.example/api" onChange={setUrl}/><FieldSelect label="请求方法" value={method} options={["POST","GET","PUT","DELETE"].map(value=>({value,label:value}))} onChange={method=>setMethod(method as AutomationConnector["method"])}/><Input label="授权环境变量名（可选）" value={authorizationEnv} placeholder="DOCWEAVE_CONNECTOR_SERVICE_TOKEN" onChange={setAuthorizationEnv}/><p className="text-caption leading-5 text-muted-foreground">只填写变量名，不要填写密码或令牌值。变量需先在服务端配置；未配置的外部能力会返回明确错误。</p><Checkbox label="启用连接器" checked={enabled} onCheckedChange={setEnabled}/>{error&&<p role="alert" className="text-body text-destructive">{error}</p>}</fieldset></div></AppModal>;
}
