import { TextEntry } from "@/components/controls";
import {Button} from "@/shared/ui";
import {base,useLoad} from "./model";
import type {AutomationFailureNotice as Config} from "./automation-model";
type Recipient={id:string;displayName:string;creator:boolean};
export function AutomationFailureNotice({id,value,onChange}:{id:string;value?:Config;onChange:(value:Config)=>void}) {
  const people=useLoad<Recipient[]>(`${base}/automations/${id}/failure-recipients`),enabled=value?.enabled??true,selected=value?.recipientIds??[];
  const rows=people.data??[],missing=selected.filter(id=>!rows.some(person=>person.id.toLowerCase()===id.toLowerCase()));
  function toggle(id:string,checked:boolean){onChange({enabled,recipientIds:checked?[...selected,id]:selected.filter(value=>value.toLowerCase()!==id.toLowerCase())});}
  return <section className="space-y-3 rounded-card border border-border p-4" aria-label="失败通知设置"><label className="flex items-center gap-2 text-body font-medium"><TextEntry type="checkbox" checked={enabled} onChange={event=>onChange({enabled:event.target.checked,recipientIds:selected})}/>运行最终失败时发送站内通知</label><p className="text-caption leading-6 text-muted-foreground">通知当前仍有效的定义创建者及所选应用管理者。等待自动重试时不通知，同一运行对同一收件人只通知一次；发布后生效。</p>{enabled&&<>{people.error?<div className="flex flex-wrap items-center gap-2"><p role="alert" className="text-caption text-destructive">{people.error}</p><Button size="sm" variant="ghost" onClick={people.refresh}>重新读取管理者</Button></div>:people.loading?<p className="text-caption text-muted-foreground">正在读取当前管理者…</p>:<div className="flex flex-wrap gap-x-5 gap-y-3">{rows.map(person=><label key={person.id} className="flex items-center gap-2 text-caption"><TextEntry type="checkbox" checked={person.creator||selected.some(id=>id.toLowerCase()===person.id.toLowerCase())} disabled={person.creator||selected.length>=20&&!selected.some(id=>id.toLowerCase()===person.id.toLowerCase())} onChange={event=>toggle(person.id,event.target.checked)}/>{person.displayName}{person.creator?"（定义创建者）":""}</label>)}{!rows.length&&<p className="text-caption text-muted-foreground">当前没有可接收通知的有效管理者。</p>}</div>}</>}{!people.loading&&!people.error&&missing.map(id=><label key={id} className="flex flex-wrap items-center gap-2 text-caption text-destructive"><TextEntry type="checkbox" checked onChange={()=>toggle(id,false)}/>已失效的收件人，请移除后保存 <span className="break-all">{id}</span></label>)}</section>;
}
