import { ActionSurface, MultilineEntry } from "@/components/controls";
import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {api} from "@/shared/api/client";
import {AppModal,Button,FieldSelect,Input} from "@/shared/ui";
import type {Directory} from "../organization/model";
import {BackLink} from "./common";
import {base,message,useLoad,type Table} from "./model";
import type {RelationTable} from "./relations";
import {AutomationStepEditor} from "./AutomationStepEditor";
import {AutomationConnectors} from "./AutomationConnectors";
import {AutomationRuns} from "./AutomationRuns";
import {AutomationDebug} from "./AutomationDebug";
import {AutomationFailureNotice} from "./AutomationFailureNotice";
import {allSteps,automationTriggers,normalizeAutomation,stepCount,uuidPattern,validateAutomation,type Automation,type AutomationConnector,type AutomationTrigger} from "./automation-model";
export function AutomationWorkspace({table,directory}:{table:Table;directory:Directory}) {
  const definitions=useLoad<Automation[]>(`${base}/tables/${table.id}/automations`),connectors=useLoad<AutomationConnector[]>(`${base}/applications/${table.appId}/automation-connectors`),tables=useLoad<RelationTable[]>(`${base}/relation-tables`),[selected,setSelected]=useState<string>(),[creating,setCreating]=useState(false),[name,setName]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[showConnectors,setShowConnectors]=useState(false),[dirty,setDirty]=useState(false);
  useEffect(()=>{if(!selected&&definitions.data?.length)setSelected(definitions.data[0].id);},[selected,definitions.data]);
  useEffect(()=>{if(!dirty)setError("");},[dirty]);
  async function create(){if(!name.trim())return;setBusy(true);setError("");try {const result=await api<Automation>(`${base}/tables/${table.id}/automations`,"POST",{name:name.trim(),draft:{trigger:{type:"BUTTON"},steps:[{id:"step1",kind:"FUNCTION",formula:{op:"CONST",value:0}}]}});setSelected(result.id);setCreating(false);setName("");definitions.refresh();}catch(e){setError(message(e));}finally{setBusy(false);}}
  return <div onClickCapture={event=>{if(dirty&&(event.target as Element).closest("a")){event.preventDefault();setError("请先保存或撤销当前草稿再离开。");}}} className="w-full min-w-0 px-4 py-5 sm:px-7"><BackLink to={`/apps/${table.appId}?table=${table.id}`}>返回 {table.name}</BackLink><header data-dw-enter="header" className="my-5 flex flex-wrap items-center gap-3"><div className="min-w-0 w-full flex-none sm:w-auto sm:flex-1"><h1 className="text-title font-medium">自动化 · {table.name}</h1><p className="mt-2 text-caption text-muted-foreground">为记录事件、计划时间和手动操作编排步骤，查看每次运行结果。</p></div><Button variant="secondary" onClick={()=>setShowConnectors(true)}>连接器管理</Button><Button onClick={()=>{if(dirty){setError("请先保存或撤销当前草稿再新建。");return;}setCreating(true);setError("");}}>新建自动化</Button></header><nav aria-label="设计器切换" className="mb-5 flex gap-5 border-b border-border pb-3 text-body"><Link to={`/apps/${table.appId}/tables/${table.id}/design`} className="text-muted-foreground">表单设计</Link><Link to={`/apps/${table.appId}/tables/${table.id}/workflow`} className="text-muted-foreground">审批流程</Link><span aria-current="page" className="font-medium text-primary">自动化</span></nav>
    {error&&!creating&&<p role="alert" className="mb-4 text-body text-destructive">{error}</p>}<div className="grid min-w-0 gap-5 xl:grid-cols-automation-settings"><aside className="space-y-2" aria-label="自动化列表">{definitions.error?<p role="alert" className="text-body text-destructive">{definitions.error}</p>:definitions.loading?<p className="text-body text-muted-foreground">正在读取自动化…</p>:!definitions.data?.length?<p className="text-body text-muted-foreground">尚无自动化，可从手动触发开始配置。</p>:definitions.data.map(automation=><ActionSurface active={automation.id===selected} key={automation.id} type="button" className="block w-full text-left" onClick={()=>{if(dirty&&selected!==automation.id){setError("请先保存或撤销当前草稿再切换。");return;}setSelected(automation.id);setError("");}}><span className="block break-words text-body font-medium">{automation.name}</span><small className="mt-1 block text-caption text-muted-foreground">{automation.enabled?"已启用":"已停用"} · {automation.publishedVersionId||automation.publishedVersion?"已有发布版本":"草稿"}</small></ActionSurface>)}<Button size="sm" variant="ghost" onClick={definitions.refresh}>刷新列表</Button></aside>{selected?<AutomationEditor key={selected} id={selected} table={table} directory={directory} tables={(tables.data??[]).filter(item=>item.appId===table.appId)} definitions={definitions.data??[]} connectors={connectors.data??[]} onSaved={definitions.refresh} onDirty={setDirty}/>:<div className="rounded-card border border-dashed border-border p-8 text-body text-muted-foreground">选择自动化查看配置或运行记录。</div>}</div>
    {showConnectors&&<AutomationConnectors appId={table.appId} connectors={connectors.data??[]} onSaved={connectors.refresh} onClose={()=>setShowConnectors(false)}/>}<AppModal open={creating} onOpenChange={open=>{if(!busy)setCreating(open);}} title="新建自动化" footer={<Button disabled={busy||!name.trim()} onClick={()=>void create()}>{busy?"正在创建…":"创建草稿"}</Button>}><Input label="自动化名称" value={name} maxLength={128} onChange={setName}/><p className="mt-3 text-caption text-muted-foreground">新草稿包含一个可编辑的计算步骤，发布并启用后才参与执行。</p>{error&&<p role="alert" className="mt-3 text-body text-destructive">{error}</p>}</AppModal>
  </div>;
}
function AutomationEditor({id,...props}:{id:string;table:Table;directory:Directory;tables:RelationTable[];definitions:Automation[];connectors:AutomationConnector[];onSaved:()=>void;onDirty:(dirty:boolean)=>void}) {const definition=useLoad<Automation>(`${base}/automations/${id}`);if(!definition.data)return <div><p className="text-body text-muted-foreground">{definition.error||"正在加载定义…"}</p><Button size="sm" variant="ghost" onClick={definition.refresh}>重新读取</Button></div>;return <AutomationEditorBody initial={normalizeAutomation(definition.data)} {...props}/>;}
function AutomationEditorBody({initial,table,directory,tables,definitions,connectors,onSaved,onDirty}:{initial:Automation;table:Table;directory:Directory;tables:RelationTable[];definitions:Automation[];connectors:AutomationConnector[];onSaved:()=>void;onDirty:(dirty:boolean)=>void}) {
  const [saved,setSaved]=useState(initial),[draft,setDraft]=useState(initial.draft),[name,setName]=useState(initial.name),[panel,setPanel]=useState("design"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[manual,setManual]=useState(false),[recordId,setRecordId]=useState(""),[dataText,setDataText]=useState("{}"),[runKey,setRunKey]=useState(()=>crypto.randomUUID()),[runId,setRunId]=useState<string>(),[token,setToken]=useState<{token:string;path?:string}>(),[targetSchemas,setTargetSchemas]=useState<Record<string,Table["publishedVersion"]>>({});
  const dirty=name!==saved.name||JSON.stringify(draft)!==JSON.stringify(saved.draft),schema=table.publishedVersion?.schema??table.draft??{name:table.name,description:"",fields:[]},issues=validateAutomation(draft,schema.fields);
  const targetIds=[...new Set(allSteps(draft.steps).map(step=>step.tableId).filter((id):id is string=>!!id))].sort().join(",");
  useEffect(()=>{onDirty(dirty);},[dirty,onDirty]);
  useEffect(()=>{const abort=new AbortController();void Promise.all(targetIds.split(",").filter(Boolean).map(async id=>{try{const target=await api<Table>(`${base}/tables/${id}?manage=true`,"GET",undefined,abort.signal);if(!abort.signal.aborted)setTargetSchemas(old=>({...old,[id]:target.publishedVersion}));}catch{if(!abort.signal.aborted)setError("无法读取部分目标表的已发布字段，请检查权限及发布状态。");}}));return()=>abort.abort();},[targetIds]);
  const fullTables=tables.map(target=>({...target,fields:target.id===table.id?schema.fields:targetSchemas[target.id]?.schema.fields??target.fields}));
  useEffect(()=>{const guard=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue="";}};window.addEventListener("beforeunload",guard);return()=>window.removeEventListener("beforeunload",guard);},[dirty]);
  async function reload(){const next=normalizeAutomation(await api<Automation>(`${base}/automations/${saved.id}`));setSaved(next);setDraft(next.draft);setName(next.name);onSaved();return next;}
  async function save(publish=false){if(issues.length||!name.trim()){setError(issues[0]??"请填写自动化名称");return;}setBusy(true);setError("");setNotice("");try{let version=saved;if(dirty){await api(`${base}/automations/${saved.id}`,"PUT",{revision:saved.revision,name,draft});version=await reload();}if(publish){await api(`${base}/automations/${saved.id}/publish`,"POST",{revision:version.revision});await reload();}setNotice(publish?"已发布；按启用状态接收触发。":"草稿已保存");}catch(e){setError(message(e));}finally{setBusy(false);}}
  async function toggle(){setBusy(true);setError("");try{await api(`${base}/automations/${saved.id}/enabled`,"POST",{revision:saved.revision,enabled:!saved.enabled});await reload();}catch(e){setError(message(e));}finally{setBusy(false);}}
  async function run(){let data:unknown;try{data=JSON.parse(dataText);if(!data||typeof data!=="object"||Array.isArray(data))throw Error();}catch{setError("手动输入需要 JSON 对象");return;}if(recordId&&!uuidPattern.test(recordId)){setError("记录 ID 格式无效");return;}setBusy(true);setError("");try{const result=await api<{id:string}>(`${base}/automations/${saved.id}/run`,"POST",{requestKey:runKey,...(recordId?{recordId}:{}),data});setRunId(result.id);setRunKey(crypto.randomUUID());setManual(false);setPanel("runs");}catch(e){setError(message(e));}finally{setBusy(false);}}
  async function rotateToken(){setBusy(true);setError("");try{const result=await api<{token:string;path?:string}>(`${base}/automations/${saved.id}/webhook-token`,"POST",{revision:saved.revision});setToken(result);await reload();}catch(e){setError(message(e));}finally{setBusy(false);}}
  function trigger(type:AutomationTrigger){setDraft({...draft,trigger:{type,...(type==="SCHEDULE"?{intervalMinutes:60}:{}),...(type==="DATE_FIELD"?{dateFieldId:schema.fields.find(field=>["date","datetime"].includes(field.type))?.id??"",offsetMinutes:0}:{})}});}
  return <section className="min-w-0 space-y-4"><header className="flex flex-wrap items-center gap-2"><h2 className="min-w-0 w-full flex-none break-words text-title font-medium sm:w-auto sm:flex-1">{saved.name}</h2><span className="text-caption text-muted-foreground">{dirty?"有未保存修改":`定义版本 ${saved.revision}`}</span><Button size="sm" variant="secondary" disabled={busy||!dirty} onClick={()=>void save()}>保存草稿</Button><Button size="sm" variant="ghost" disabled={busy||!dirty} onClick={()=>{setDraft(saved.draft);setName(saved.name);setError("");}}>撤销草稿修改</Button><Button size="sm" disabled={busy} onClick={()=>void save(true)}>发布</Button><Button size="sm" variant="outline" disabled={busy||dirty||!(saved.publishedVersionId||saved.publishedVersion)} onClick={()=>void toggle()}>{saved.enabled?"停用":"启用"}</Button><Button size="sm" variant="outline" disabled={busy||dirty||!saved.enabled||(saved.publishedVersion?.definition?.trigger.type??saved.publishedVersion?.draft?.trigger.type)!=="BUTTON"} onClick={()=>{setManual(true);setError("");setRunKey(crypto.randomUUID());}}>手动执行</Button></header><div className="flex gap-2" role="tablist" aria-label="自动化面板"><ActionSurface type="button" role="tab" aria-selected={panel==="design"}  onClick={()=>setPanel("design")}>设计</ActionSurface><ActionSurface type="button" role="tab" aria-selected={panel==="runs"}  onClick={()=>setPanel("runs")}>运行记录</ActionSurface><ActionSurface type="button" role="tab" aria-selected={panel==="debug"}  onClick={()=>setPanel("debug")}>调试预览</ActionSurface></div>{error&&<p role="alert" className="rounded-control bg-destructive/5 p-3 text-body text-destructive">{error}</p>}{notice&&<p role="status" className="text-caption text-muted-foreground">{notice}</p>}
    {panel==="runs"?<AutomationRuns automationId={saved.id} initialRunId={runId}/>:panel==="debug"?<AutomationDebug key={saved.revision} automation={saved} dirty={dirty}/>:<fieldset disabled={busy} className="min-w-0 space-y-5"><div className="grid gap-4 rounded-card border border-border p-4 md:grid-cols-2"><Input label="自动化名称" value={name} maxLength={128} onChange={setName}/><FieldSelect label="触发方式" value={draft.trigger.type} options={(Object.keys(automationTriggers) as AutomationTrigger[]).map(value=>({value,label:automationTriggers[value]}))} onChange={type=>trigger(type as AutomationTrigger)}/>{draft.trigger.type==="SCHEDULE"&&<Input label="执行间隔（分钟）" type="number" min={1} max={525600} value={String(draft.trigger.intervalMinutes??60)} onChange={value=>setDraft({...draft,trigger:{...draft.trigger,intervalMinutes:Number(value)}})}/>} {draft.trigger.type==="DATE_FIELD"&&<><FieldSelect label="日期字段" value={draft.trigger.dateFieldId??""} options={schema.fields.filter(field=>["date","datetime"].includes(field.type)).map(field=>({value:field.id,label:field.label}))} onChange={dateFieldId=>setDraft({...draft,trigger:{...draft.trigger,dateFieldId}})}/><Input label="时间偏移（分钟，负数提前）" type="number" min={-525600} max={525600} value={String(draft.trigger.offsetMinutes??0)} onChange={value=>setDraft({...draft,trigger:{...draft.trigger,offsetMinutes:Number(value)}})}/></>}{draft.trigger.type==="WEBHOOK"&&<div className="space-y-2 md:col-span-2"><Button size="sm" variant="outline" disabled={dirty||busy} onClick={()=>void rotateToken()}>生成 / 轮换 Webhook 令牌</Button><p className="text-caption text-muted-foreground">令牌只显示一次；轮换后旧令牌失效。请保存后再生成。</p></div>}</div><AutomationFailureNotice id={saved.id} value={draft.failureNotice} onChange={failureNotice=>setDraft({...draft,failureNotice})}/><div className="flex flex-wrap items-center gap-3"><h3 className="text-body font-medium">执行步骤</h3><span className="text-caption text-muted-foreground">{stepCount(draft.steps)} / 50 个声明步骤 · 最多 5 层 · 单次最多 250 个运行步骤</span></div><AutomationStepEditor steps={draft.steps} onChange={steps=>setDraft({...draft,steps})} rootSteps={draft.steps} schema={schema} directory={directory} tables={fullTables} automations={definitions.filter(item=>item.id!==saved.id)} connectors={connectors} disabled={busy}/>{issues.length>0&&<p role="alert" className="text-caption text-destructive">{issues[0]}</p>}</fieldset>}
    <AppModal open={manual} onOpenChange={open=>{if(!busy)setManual(open);}} title="手动执行自动化" description="执行已发布版本。操作会产生实际记录、通知或外部请求。" dismissible={!busy} footer={<Button disabled={busy} onClick={()=>void run()}>{busy?"正在提交…":"执行已发布版本"}</Button>}><div className="space-y-4"><Input label="关联记录 ID（可选）" value={recordId} onChange={value=>{setRecordId(value);setRunKey(crypto.randomUUID());}}/><details><summary className="cursor-pointer text-body">输入结构化测试数据（JSON 对象）</summary><MultilineEntry aria-label="手动执行数据" rows={8} className="mt-3 w-full" value={dataText} onChange={event=>{setDataText(event.target.value);setRunKey(crypto.randomUUID());}}/></details>{error&&<p role="alert" className="text-body text-destructive">{error}</p>}</div></AppModal>
    <AppModal open={!!token} onOpenChange={open=>{if(!open)setToken(undefined);}} title="保存 Webhook 凭据" description="仅本次显示。关闭后需重新轮换才能取得新令牌。"><Input label="Webhook 令牌" readOnly value={token?.token??""}/>{token?.path&&<Input label="Webhook 地址" readOnly value={`${window.location.origin}${token.path}`}/>}</AppModal>
  </section>;
}
