import { MultilineEntry } from "@/components/controls";
import {useState} from "react";
import {Button,FieldSelect,Input} from "@/shared/ui";
import type {LowcodeField} from "./field-model";
import {automationKey,bindingError,type AutomationBinding,type AutomationStep} from "./automation-model";
type BindingMode="text"|"number"|"boolean"|"json"|"field"|"path";
export function AutomationBindingEditor({label,value,onChange,fields,availableSteps,disabled}:{label:string;value:AutomationBinding;onChange:(binding:AutomationBinding)=>void;fields:LowcodeField[];availableSteps:AutomationStep[];disabled?:boolean}) {
  const [mode,setMode]=useState<BindingMode>("path" in value?value.path.startsWith("trigger.data.")?"field":"path":typeof value.literal==="number"?"number":typeof value.literal==="boolean"?"boolean":typeof value.literal==="string"?"text":"json"),[json,setJson]=useState(()=>JSON.stringify("literal" in value?value.literal:null,null,2)??"");
  const literal="literal" in value?value.literal:"",path="path" in value?value.path:"",error=bindingError(value);
  function changeMode(next:BindingMode){setMode(next);if(next==="field")onChange({path:`trigger.data.${fields[0]?.id??""}`});else if(next==="path")onChange({path:"trigger.recordId"});else if(next==="number")onChange({literal:0});else if(next==="boolean")onChange({literal:true});else if(next==="json"){setJson(JSON.stringify(literal??null,null,2));onChange({literal:literal??null});}else onChange({literal:""});}
  return <div className="min-w-0 space-y-2 rounded-control bg-muted/20 p-3"><FieldSelect label={`${label} · 来源`} value={mode} options={[{value:"text",label:"固定文本"},{value:"number",label:"固定数字"},{value:"boolean",label:"是 / 否"},{value:"field",label:"触发记录字段"},{value:"path",label:"步骤输出 / 变量"},{value:"json",label:"结构化 JSON"}]} onChange={value=>changeMode(value as BindingMode)}/>
    {mode==="text"?<Input label={label} value={String(literal??"")} disabled={disabled} onChange={text=>onChange({literal:text})}/>:mode==="number"?<Input label={label} type="number" value={literal===undefined?"":String(literal)} disabled={disabled} onChange={text=>onChange({literal:text!==""&&Number.isFinite(Number(text))?Number(text):undefined})}/>:mode==="boolean"?<FieldSelect label={label} value={String(literal)} options={[{value:"true",label:"是"},{value:"false",label:"否"}]} onChange={value=>onChange({literal:value==="true"})}/>:mode==="field"?<FieldSelect label={label} value={path.replace(/^trigger\.data\./,"")} options={fields.map(field=>({value:field.id,label:field.label}))} onChange={id=>onChange({path:`trigger.data.${id}`})}/>:mode==="path"?<><FieldSelect label={`${label} · 常用变量`} value={path} options={[{value:"trigger.recordId",label:"触发记录 ID"},{value:"trigger.revision",label:"触发记录内容版本"},{value:"trigger.data",label:"触发记录全部字段"},{value:"item",label:"循环当前项"},...availableSteps.flatMap(step=>[{value:`steps.${step.id}`,label:`${step.id} · 完整输出`},{value:`steps.${step.id}.items`,label:`${step.id} · 查询列表`},{value:`steps.${step.id}.value`,label:`${step.id} · 计算结果`},{value:`steps.${step.id}.recordId`,label:`${step.id} · 记录 ID`},...(step.kind==="ORG_QUERY"?[{value:`steps.${step.id}.userIds`,label:`${step.id} · 组织成员 ID 列表`},{value:`steps.${step.id}.hasMore`,label:`${step.id} · 是否还有更多成员`}]:[])])]} onChange={path=>onChange({path})}/><Input label={`${label} · 变量路径`} value={path} placeholder="steps.step1.items 或 item.id" disabled={disabled} onChange={path=>onChange({path})}/></>:<label className="block space-y-1 text-caption text-muted-foreground"><span>{label} · JSON</span><MultilineEntry aria-label={`${label} · JSON`} rows={5} value={json} disabled={disabled} className="w-full" onChange={event=>{setJson(event.target.value);try{onChange({literal:JSON.parse(event.target.value)});}catch{onChange({literal:undefined});}}}/></label>}
    {error&&<p role="alert" className="text-caption text-destructive">{error}</p>}
  </div>;
}
export function AutomationMappingEditor({label,value={},onChange,fields,targetFields,availableSteps,disabled,knownKeys=[],numeric=false,maxEntries=50,allowCustom=false}:{label:string;value?:Record<string,AutomationBinding>;onChange:(value:Record<string,AutomationBinding>)=>void;fields:LowcodeField[];targetFields?:LowcodeField[];availableSteps:AutomationStep[];disabled?:boolean;knownKeys?:{value:string;label:string}[];numeric?:boolean;maxEntries?:number;allowCustom?:boolean}) {
  const [name,setName]=useState(""),[custom,setCustom]=useState(false),keys=targetFields?.map(field=>({value:field.id,label:field.label}))??knownKeys,remaining=keys.filter(key=>!Object.hasOwn(value,key.value));
  return <fieldset disabled={disabled} className="min-w-0 space-y-3"><legend className="mb-2 text-caption font-medium">{label}</legend>{Object.entries(value).map(([key,binding])=><div key={key} className="space-y-2 rounded-card border border-border p-3"><div className="flex items-center gap-2"><span className="min-w-0 flex-1 text-body font-medium">{keys.find(entry=>entry.value===key)?.label??key}</span><Button size="sm" variant="ghost" aria-label={`移除映射 ${key}`} onClick={()=>onChange(Object.fromEntries(Object.entries(value).filter(([id])=>id!==key)))}>移除</Button></div><AutomationBindingEditor label={key} value={binding} onChange={binding=>onChange({...value,[key]:binding})} fields={fields} availableSteps={availableSteps} disabled={disabled}/></div>)}<div className="flex flex-wrap items-end gap-2"><div className="min-w-36 flex-1">{keys.length&&!custom?<FieldSelect label={`添加${label}`} value={name} options={remaining} onChange={setName}/>:<Input label={`添加${label}`} value={name} placeholder="参数名称，如 message" onChange={setName}/>}</div><Button size="sm" variant="outline" disabled={disabled||!(targetFields?/^[A-Za-z][A-Za-z0-9]{0,63}$/.test(name):automationKey(name))||Object.hasOwn(value,name)||Object.keys(value).length>=maxEntries} onClick={()=>{const target=targetFields?.find(field=>field.id===name);onChange({...value,[name]:{literal:numeric||target?.type==="number"?0:target?.type==="checkbox"?false:""}});setName("");}}>添加映射</Button>{allowCustom&&keys.length>0&&<Button size="sm" variant="ghost" onClick={()=>{setCustom(!custom);setName("");}}>{custom?"常用参数":"自定义参数"}</Button>}</div></fieldset>;
}
