import { SelectEntry } from "@/components/controls";
import {Button,FieldSelect,Input} from "@/shared/ui";
import type {TableSchema} from "./field-model";
import type {FormLayout} from "./form-layouts";
type SchemaWithLayouts=TableSchema & {layouts?:FormLayout[];defaultLayoutId?:string};
export function FormLayoutSettings({schema,onChange,disabled}:{schema:SchemaWithLayouts;onChange:(schema:SchemaWithLayouts)=>void;disabled?:boolean}) {
 const layouts=schema.layouts??[];
 const update=(id:string,patch:Partial<FormLayout>)=>onChange({...schema,layouts:layouts.map(layout=>layout.id===id?{...layout,...patch}:layout)});
 return <details className="mb-5 rounded-card border border-border bg-card p-4"><summary className="cursor-pointer text-body font-medium">多布局设置</summary><fieldset disabled={disabled} className="mt-4 space-y-4"><p className="text-caption leading-5 text-muted-foreground">为同一表单提供不同的字段顺序和宽度。切换布局会保留已填写内容，所有字段仍按原规则显示和校验。</p>
 <FieldSelect label="默认布局" value={schema.defaultLayoutId??""} options={[{value:"",label:"原始布局"},...layouts.map(layout=>({value:layout.id,label:layout.name}))]} onChange={defaultLayoutId=>onChange({...schema,defaultLayoutId:defaultLayoutId||undefined})}/>
 {layouts.map(layout=>{const order=[...new Set([...layout.fieldOrder,...schema.fields.map(field=>field.id)])].filter(id=>schema.fields.some(field=>field.id===id));return <details key={layout.id} className="rounded-card border border-border p-3"><summary className="cursor-pointer text-body">{layout.name}</summary><div className="mt-3 space-y-3"><Input label="布局名称" maxLength={40} value={layout.name} onChange={name=>update(layout.id,{name})}/><FieldSelect label="默认列数" value={String(layout.columns)} options={[1,2,3,4].map(n=>({value:String(n),label:`${n} 列`}))} onChange={columns=>update(layout.id,{columns:Number(columns) as FormLayout["columns"]})}/>
 <div className="max-h-80 space-y-2 overflow-auto">{order.map((id,index)=><div key={id} className="flex flex-wrap items-center gap-2 rounded-control bg-muted/30 p-2"><span className="min-w-20 flex-1 text-caption">{schema.fields.find(field=>field.id===id)?.label}</span><SelectEntry aria-label={`${layout.name}-${id}-字段宽度`}  value={layout.widths?.[id]??""} onChange={event=>{const widths={...layout.widths};if(event.target.value)widths[id]=Number(event.target.value);else delete widths[id];update(layout.id,{widths});}}><option value="">默认宽度</option>{[12,9,8,6,4,3].map(width=><option key={width} value={width}>{width} / 12</option>)}</SelectEntry><Button variant="ghost" size="sm" disabled={disabled||index===0} onClick={()=>{const fieldOrder=[...order];[fieldOrder[index-1],fieldOrder[index]]=[fieldOrder[index],fieldOrder[index-1]];update(layout.id,{fieldOrder});}}>上移</Button></div>)}</div>
 <Button variant="ghost" size="sm" onClick={()=>{const next=layouts.filter(item=>item.id!==layout.id);onChange({...schema,layouts:next.length?next:undefined,defaultLayoutId:schema.defaultLayoutId===layout.id?undefined:schema.defaultLayoutId});}}>删除此布局</Button></div></details>;})}
 <Button variant="outline" size="sm" disabled={disabled||layouts.length>=6} onClick={()=>onChange({...schema,layouts:[...layouts,{id:`l${crypto.randomUUID().replaceAll("-","")}`,name:`布局 ${layouts.length+1}`,columns:2,fieldOrder:schema.fields.map(field=>field.id)}]})}>添加布局</Button></fieldset></details>;
}
