import { ActionSurface } from "@/components/controls";
import {useEffect,useState} from "react";
import {Button} from "@/shared/ui";
import {api} from "@/shared/api/client";
import {PeoplePickerField} from "../organization/PeoplePicker";
import type {Directory} from "../organization/model";
import {FieldRenderer} from "./FieldRenderer";
import {isFieldVisible,type LowcodeField,type TableSchema} from "./field-model";
import {ruleMatches} from "./rules";
import {base,dateLabel,message,useLoad,type Row,type RecordWorkflow} from "./model";
import {defaultDetail,detailLabels,recordTitle,type DetailSection} from "./record-presentation";
import {RecordWorkflows} from "./RecordWorkflows";
import {RecordPrint} from "./RecordPrint";
import {AutomationRecordActions} from "./AutomationRecordActions";
import {ApprovalRecordActions} from "./ApprovalRecordActions";
type Ownership={ownerId:string;ownerName:string;collaboratorIds:string[];collaborators:{id:string;name:string}[];revision:number;canManage:boolean;history:{revision:number;createdAt:string;actorName:string;beforeValue:{ownerId:string};afterValue:{ownerId:string}}[]};
function attachmentEntries(schema:TableSchema,data:Record<string,unknown>,prefix=""): {field:LowcodeField;value:unknown;label:string}[] {
  return schema.fields.flatMap(field=>{if(!isFieldVisible(field,"edit",true)||field.visibleWhen&&!ruleMatches(field.visibleWhen,data,schema.fields))return[];
    if(field.type==="subtable"&&field.subtableConfig&&Array.isArray(data[field.id]))return (data[field.id] as {id:string;values:Record<string,unknown>}[]).flatMap((row,index)=>attachmentEntries({name:"",description:"",fields:field.subtableConfig!.fields},row.values,`${prefix}${field.label} · 第${index+1}行 · `));
    if(!["attachment","image","signature","displayImage"].includes(field.type))return[];
    const value=field.type==="displayImage"?field.imageConfig?.fileIds:data[field.id];if(!value||Array.isArray(value)&&!value.length)return[];
    const copy={...field,width:12};delete copy.visibleWhen;delete copy.warningRules;return [{field:copy,value,label:`${prefix}${field.label}`}];});
}
export function RecordDetail({row,schema,directory,onOwnershipChanged}:{row:Row;schema:TableSchema;directory:Directory;onOwnershipChanged?:()=>void}) {
  const detail=schema.detailConfig??defaultDetail,[section,setSection]=useState<DetailSection>(detail.sections[0]),[printing,setPrinting]=useState(false),ownership=useLoad<Ownership>(`${base}/records/${row.id}/ownership`),workflows=useLoad<RecordWorkflow[]>(detail.sections.includes("workflow")?`${base}/records/${row.id}/workflows`:undefined);
  const [editOwnership,setEditOwnership]=useState(false),[owner,setOwner]=useState(""),[collaborators,setCollaborators]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[requestKey,setRequestKey]=useState(()=>crypto.randomUUID());
  useEffect(()=>{if(ownership.data){setOwner(ownership.data.ownerId);setCollaborators(ownership.data.collaboratorIds);}},[ownership.data]);
  useEffect(()=>{if(!detail.sections.includes(section))setSection(detail.sections[0]);},[detail.sections,section]);
  async function saveOwnership(){if(!ownership.data||busy)return;setBusy(true);setError("");try{await api(`${base}/records/${row.id}/ownership`,"PUT",{ownerId:owner,collaboratorIds:collaborators.filter(id=>id!==owner),revision:ownership.data.revision,idempotencyKey:requestKey});setEditOwnership(false);setRequestKey(crypto.randomUUID());ownership.refresh();onOwnershipChanged?.();}catch(e){setError(message(e));}finally{setBusy(false);}}
  const files=attachmentEntries(schema,row.data),context={tableId:row.tableId,recordId:row.id};
  function body(current:DetailSection){
    if(current==="overview")return <div className="space-y-6"><section className="space-y-3 rounded-card border border-border p-4"><h3 className="text-body font-medium">业务归属</h3>{ownership.loading?<p className="text-caption text-muted-foreground">正在读取归属…</p>:ownership.error?<div><p role="alert" className="text-body text-destructive">{ownership.error}</p><Button size="sm" variant="ghost" onClick={ownership.refresh}>重新读取归属</Button></div>:<><p className="text-body">负责人：{ownership.data?.ownerName||"—"}</p><p className="text-body">协作者：{ownership.data?.collaborators.map(person=>person.name).join("、")||"未设置"}</p>{ownership.data?.canManage&&!editOwnership&&<Button size="sm" variant="outline" onClick={()=>{setError("");setRequestKey(crypto.randomUUID());setEditOwnership(true);}}>调整负责人和协作者</Button>}</>}{editOwnership&&<div className="space-y-3 border-t border-border pt-3"><label htmlFor="record-owner" className="block text-caption text-muted-foreground">业务负责人</label><PeoplePickerField id="record-owner" label="业务负责人" directory={directory} value={owner?[owner]:[]} multiple={false} disabled={busy} onChange={ids=>{setOwner(ids[0]??"");setRequestKey(crypto.randomUUID());}}/><label htmlFor="record-collaborators" className="block text-caption text-muted-foreground">记录协作者</label><PeoplePickerField id="record-collaborators" label="记录协作者" directory={directory} value={collaborators} multiple limit={50} disabled={busy} eligible={person=>person.id!==owner} onChange={ids=>{setCollaborators(ids);setRequestKey(crypto.randomUUID());}}/><p className="text-caption leading-5 text-muted-foreground">负责人和协作者需有该表的读取权限，负责人还需有修改权限。移交后你的可用操作会按当前表权限重新计算。</p><div className="flex gap-2"><Button size="sm" disabled={busy||!owner} onClick={()=>void saveOwnership()}>{busy?"正在保存…":"保存归属"}</Button><Button size="sm" variant="ghost" disabled={busy} onClick={()=>setEditOwnership(false)}>取消</Button></div>{error&&<p role="alert" className="text-body text-destructive">{error}</p>}</div>}</section><FieldRenderer schema={{...schema,name:"",description:""}} value={row.data} onChange={()=>{}} directory={directory} readOnly mode="edit" fileContext={context}/></div>;
    if(current==="history")return <div className="space-y-5"><div><h3 className="mb-3 text-body font-medium">记录内容变更</h3>{row.history?.length?row.history.map(item=><div key={item.revision} className="flex flex-wrap gap-3 border-b border-border py-3 text-body"><span>V{item.revision}</span><span>{({CREATE:"新增",UPDATE:"修改",DELETE:"删除"} as Record<string,string>)[item.action]??item.action}</span><span>{item.actorName}</span><time className="text-caption text-muted-foreground">{dateLabel(item.createdAt)}</time></div>):<p className="text-body text-muted-foreground">尚无内容变更记录。</p>}</div><div><h3 className="mb-3 text-body font-medium">归属变更</h3>{ownership.data?.history.length?ownership.data.history.map(item=><p key={item.revision} className="border-b border-border py-3 text-body">归属版本 {item.revision} · {item.actorName} · {dateLabel(item.createdAt)}</p>):<p className="text-body text-muted-foreground">尚无归属调整记录。</p>}</div></div>;
    if(current==="workflow")return workflows.error?<div><p role="alert" className="text-body text-destructive">{workflows.error}</p><Button variant="ghost" onClick={workflows.refresh}>重新读取流程</Button></div>:workflows.loading?<p className="text-body text-muted-foreground">正在读取流程…</p>:<RecordWorkflows runs={workflows.data??[]} currentRevision={row.revision} onRefresh={workflows.refresh}/>;
    return files.length?<div className="space-y-5">{files.map((entry,index)=><section key={`${entry.label}-${index}`}><h3 className="mb-2 text-body font-medium">{entry.label}</h3><FieldRenderer schema={{name:"",description:"",fields:[{...entry.field,label:entry.label}]}} value={{[entry.field.id]:entry.value}} onChange={()=>{}} directory={directory} readOnly mode="edit" fileContext={context}/></section>)}</div>:<p className="text-body text-muted-foreground">当前记录没有附件、图片或签名。</p>;
  }
  return <div className="space-y-5"><header className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h2 className="break-words text-title font-semibold">{recordTitle(schema,row.data,row.title)}</h2><p className="mt-2 text-caption text-muted-foreground">创建人 {row.creatorName||"—"} · {dateLabel(row.createdAt)} · 内容版本 V{row.revision}</p></div><div className="flex flex-wrap gap-2"><ApprovalRecordActions row={row}/><AutomationRecordActions row={row}/><Button variant="outline" size="sm" onClick={()=>setPrinting(true)}>打印记录</Button></div></header>{detail.layout==="tabs"?<><div role="tablist" aria-label="记录详情分区" className="flex flex-wrap gap-2 border-b border-border pb-3">{detail.sections.map(item=><ActionSurface active={section===item} key={item} type="button" role="tab" id={`record-tab-${item}`} aria-controls={`record-panel-${item}`} aria-selected={section===item}  onClick={()=>setSection(item)}>{detailLabels[item]}</ActionSurface>)}</div><section role="tabpanel" id={`record-panel-${section}`} aria-labelledby={`record-tab-${section}`}>{body(section)}</section></>:detail.sections.map(item=><section key={item} className="space-y-4 border-t border-border pt-5"><h2 className="font-medium">{detailLabels[item]}</h2>{body(item)}</section>)}{printing&&<RecordPrint row={row} schema={schema} directory={directory} onClose={()=>setPrinting(false)}/>}</div>;
}
