import {Button,FieldSelect} from "@/shared/ui";
import {PrintTemplateSettings} from "./PrintTemplateSettings";
import {Checkbox} from "@/components/motion/checkbox";
import type {TableSchema} from "./field-model";
import {defaultDetail,detailLabels,printableField,titleSource,type DetailSection} from "./record-presentation";
export function RecordPresentationSettings({schema,onChange,disabled}:{schema:TableSchema;onChange:(schema:TableSchema)=>void;disabled?:boolean}) {
  const detail=schema.detailConfig??defaultDetail,print=schema.printConfig;
  return <details className="mb-5 rounded-card border border-border bg-card p-4"><summary className="cursor-pointer text-body font-medium">记录标题、详情与打印</summary><div className="mt-4 grid gap-6 lg:grid-cols-3">
    <fieldset disabled={disabled} className="space-y-3"><h3 className="text-body font-medium">记录标题</h3><FieldSelect label="标题来源字段" value={schema.titleFieldId??""} options={[{value:"",label:"使用记录提交标题"},...schema.fields.filter(titleSource).map(field=>({value:field.id,label:field.label}))]} onChange={titleFieldId=>onChange({...schema,titleFieldId:titleFieldId||undefined})}/><p className="text-caption leading-5 text-muted-foreground">从服务端保存后的字段值生成，最多 200 个字符；空值使用原记录或表名称。创建人保留在独立审计信息中。</p></fieldset>
    <fieldset disabled={disabled} className="space-y-3"><h3 className="text-body font-medium">详情分区</h3><FieldSelect label="详情显示方式" value={detail.layout} options={[{value:"tabs",label:"标签切换"},{value:"sections",label:"顺序分区"}]} onChange={layout=>onChange({...schema,detailConfig:{...detail,layout:layout as "tabs"|"sections"}})}/>{(Object.keys(detailLabels) as DetailSection[]).map(section=><div key={section} className="flex items-center gap-1"><Checkbox  label={detailLabels[section]} checked={detail.sections.includes(section)} disabled={disabled||section==="overview"} onCheckedChange={checked=>onChange({...schema,detailConfig:{...detail,sections:checked?[...detail.sections,section]:detail.sections.filter(item=>item!==section)}})}/>{detail.sections.includes(section)&&<Button size="sm" variant="ghost" disabled={disabled||detail.sections.indexOf(section)===0} onClick={()=>{const sections=[...detail.sections],index=sections.indexOf(section);[sections[index-1],sections[index]]=[sections[index],sections[index-1]];onChange({...schema,detailConfig:{...detail,sections}});}}>上移</Button>}</div>)}</fieldset>
    <fieldset disabled={disabled} className="space-y-3"><h3 className="text-body font-medium">打印模板</h3><Checkbox label="配置打印默认字段与布局" checked={!!print} onCheckedChange={checked=>onChange({...schema,printConfig:checked?{fieldIds:schema.fields.filter(printableField).map(field=>field.id),columns:1,orientation:"portrait",showMetadata:true}:undefined})}/>{print&&<><FieldSelect label="打印列数" value={String(print.columns)} options={[{value:"1",label:"单列"},{value:"2",label:"双列"}]} onChange={columns=>onChange({...schema,printConfig:{...print,columns:Number(columns) as 1|2}})}/><FieldSelect label="纸张方向" value={print.orientation} options={[{value:"portrait",label:"A4 纵向"},{value:"landscape",label:"A4 横向"}]} onChange={orientation=>onChange({...schema,printConfig:{...print,orientation:orientation as "portrait"|"landscape"}})}/><Checkbox label="打印创建人、时间与版本" checked={print.showMetadata} onCheckedChange={showMetadata=>onChange({...schema,printConfig:{...print,showMetadata}})}/><div className="max-h-56 space-y-2 overflow-auto">{schema.fields.filter(printableField).map(field=><Checkbox key={field.id} className="w-full" label={field.label} checked={print.fieldIds.includes(field.id)} onCheckedChange={checked=>onChange({...schema,printConfig:{...print,fieldIds:checked?[...print.fieldIds,field.id]:print.fieldIds.filter(id=>id!==field.id)}})}/>)}</div></>}</fieldset>
  </div><PrintTemplateSettings schema={schema} onChange={onChange} disabled={disabled}/></details>;
}
