import {useState} from "react";
import {Link} from "react-router-dom";
import {api} from "@/shared/api/client";
import {Button} from "@/shared/ui";
import {base,dateLabel,message,statuses,type RecordWorkflow} from "./model";

const executionLabels:Record<string,string>={QUEUED:"等待启动",STARTING:"正在启动",RETRY:"等待重试",FAILED:"执行失败",RUNNING:"正在执行",WAITING:"等待处理",DONE:"执行结束"};
const resultLabels:Record<string,string>={NONE:"尚无审批结果",PENDING:"审批中",APPROVED:"已通过",PASSED:"已通过",REJECTED:"不通过",WITHDRAWN:"已撤回",RETURNED:"待修改"};
export function RecordWorkflows({runs,currentRevision,onRefresh}:{runs:RecordWorkflow[];currentRevision?:number;onRefresh:()=>void}) {
  const [busy,setBusy]=useState<string>(),[error,setError]=useState("");
  async function retry(run:RecordWorkflow){if(busy)return;setBusy(run.id);setError("");try{await api(`${base}/flow-runs/${run.id}/retry`,"POST",{});onRefresh();}catch(cause){setError(message(cause));}finally{setBusy(undefined);}}
  return <div className="space-y-3"><div className="flex items-center justify-between gap-3"><p className="text-caption leading-5 text-muted-foreground">各流程独立处理自己的记录版本。</p><Button size="sm" variant="ghost" disabled={!!busy} onClick={onRefresh}>刷新状态</Button></div>{error&&<p role="alert" className="text-body text-destructive">{error}</p>}{runs.length?runs.map(run=><section key={run.id} className="space-y-2 rounded-card border border-border p-4"><h3 className="text-body font-medium">{run.flowName||"审批流程"}</h3><p className="text-caption text-muted-foreground">流程 V{run.flowVersion} · 记录 V{run.recordRevision}{currentRevision!==undefined&&run.recordRevision<currentRevision?"（历史版本）":""}</p><dl className="grid grid-cols-auto-content gap-x-3 gap-y-1 text-body"><dt className="text-muted-foreground">审批结果</dt><dd>{resultLabels[run.approvalResult]??statuses[run.status]??run.approvalResult??"尚无审批结果"}</dd><dt className="text-muted-foreground">执行状态</dt><dd>{executionLabels[run.executionState]??run.executionState}</dd></dl>{!!run.conflictCount&&<p role="status" className="text-caption text-status-warning">{run.conflictCount} 项字段回填发生冲突，当前记录保留已有值。</p>}{run.error&&<p className="break-words text-caption text-destructive">{run.error}</p>}<p className="text-caption text-muted-foreground">{dateLabel(run.createdAt)}{run.completedAt?` → ${dateLabel(run.completedAt)}`:""}</p><div className="flex flex-wrap items-center gap-3">{run.canOpen&&<Link className="text-body text-primary underline underline-offset-4" to={`/workflows/${run.changeId}?run=${encodeURIComponent(run.id)}`}>查看此流程</Link>}{run.canRetry&&run.executionState==="FAILED"&&<Button size="sm" variant="outline" disabled={!!busy} onClick={()=>void retry(run)}>{busy===run.id?"正在重试…":"重试启动"}</Button>}</div></section>):<p className="text-body text-muted-foreground">此记录尚无关联流程。</p>}</div>;
}
