import {ArrowDown,ArrowUp} from "@/shared/icons/catalog";
import {PlusAction,TrashAction} from "@/shared/icons/motion";
import {Button,FieldSelect,Input} from "@/shared/ui";
import {Checkbox} from "@/components/motion/checkbox";
import type {Directory} from "../organization/model";
import type {LowcodeField} from "./field-model";
import {blankDirectory,useLoad} from "./model";
import {RuleEditor} from "./RuleEditor";
import {RelationFilterEditor} from "./RelationFilterEditor";
import {relationRuleFields,lookupNumberSource,lookupTextSource,type RelationConfig,type RelationTable,type RelationTarget} from "./relations";

export function RelationTargetSettings({value,fields,tables,onChange,disabled}:{value:RelationConfig;fields:LowcodeField[];tables:RelationTable[];onChange:(value:RelationConfig)=>void;disabled:boolean}) {
  const entries=value.targets??[],directory=useLoad<Directory>(entries.length?"/api/v1/organization":undefined),sources=relationRuleFields(fields);
  function update(index:number,patch:Partial<RelationTarget>){onChange({...value,targets:entries.map((entry,i)=>i===index?{...entry,...patch}:entry)});}
  function move(index:number,delta:number){const next=[...entries];[next[index],next[index+delta]]=[next[index+delta],next[index]];onChange({...value,targets:next});}
  function add(){let index=1;while(entries.some(entry=>entry.id===`target${index}`))index++;onChange({...value,targets:[...entries,{id:`target${index}`,name:`条件来源 ${entries.length+1}`,tableId:"",when:{fieldId:sources[0]?.id??"",operator:"NOT_EMPTY"}}]});}
  return <section className="min-w-0 space-y-3 border-t border-border pt-3" aria-label="条件关联来源"><div className="flex flex-wrap items-center justify-between gap-2"><h4 className="text-caption font-medium">按条件切换关联来源</h4><Button size="sm" variant="outline" disabled={disabled||entries.length>=8||!sources.length} onClick={add}><PlusAction size={13}/>添加条件来源</Button></div><p className="text-caption leading-5 text-muted-foreground">从上到下使用第一个满足条件的来源，否则使用上方默认关联表。条件只引用同层原始字段；切换目标表会清空当前选择。</p>
    {entries.map((entry,index)=>{const table=tables.find(table=>table.id.toLowerCase()===entry.tableId.toLowerCase());return <section key={entry.id} className="min-w-0 space-y-3 rounded-control border border-border p-3"><div className="flex flex-wrap items-center gap-2"><span className="flex-1 text-caption font-medium">来源 {index+1} · {entry.id}</span><Button size="icon" variant="ghost" aria-label={`上移来源 ${index+1}`} disabled={disabled||index===0} onClick={()=>move(index,-1)}><ArrowUp size={13}/></Button><Button size="icon" variant="ghost" aria-label={`下移来源 ${index+1}`} disabled={disabled||index===entries.length-1} onClick={()=>move(index,1)}><ArrowDown size={13}/></Button><Button size="icon" variant="ghost" aria-label={`删除来源 ${index+1}`} disabled={disabled} onClick={()=>onChange({...value,targets:entries.filter((_,i)=>i!==index)})}><TrashAction size={13}/></Button></div><Input label="来源名称" value={entry.name} maxLength={80} onChange={name=>update(index,{name})}/><RuleEditor value={entry.when} onChange={when=>update(index,{when})} fields={sources} directory={directory.data??blankDirectory} disabled={disabled}/><FieldSelect label="条件关联数据表" value={entry.tableId} options={tables.map(table=>({value:table.id,label:`${table.appName} · ${table.name}`}))} onChange={tableId=>update(index,{tableId,titleFieldId:undefined,filter:undefined,cascade:undefined})}/><FieldSelect label="条件来源显示标题" value={entry.titleFieldId??""} options={[{value:"",label:"默认记录标题"},...(table?.fields??[]).filter(field=>lookupTextSource(field)||lookupNumberSource(field)).map(field=>({value:field.id,label:field.label}))]} onChange={titleFieldId=>update(index,{titleFieldId:titleFieldId||undefined})}/><RelationFilterEditor value={entry.filter} onChange={filter=>update(index,{filter})} sources={fields} targets={table?.fields??[]} disabled={disabled}/>
      <Checkbox label="此来源按父字段逐级选择" checked={!!entry.cascade} disabled={disabled||!!value.multiple} onCheckedChange={checked=>update(index,{cascade:checked?{parentFieldId:"",leafOnly:true,maxDepth:10}:undefined})}/>{entry.cascade&&<div className="space-y-3"><FieldSelect label="此来源父记录字段" value={entry.cascade.parentFieldId} options={(table?.fields??[]).filter(field=>field.type==="relation"&&!field.relationConfig?.multiple&&!field.relationConfig?.cascade&&!field.relationConfig?.targets?.length&&field.relationConfig?.tableId.toLowerCase()===entry.tableId.toLowerCase()).map(field=>({value:field.id,label:field.label}))} onChange={parentFieldId=>update(index,{cascade:{...entry.cascade!,parentFieldId}})}/><Checkbox label="此来源只能选末级" checked={entry.cascade.leafOnly!==false} onCheckedChange={leafOnly=>update(index,{cascade:{...entry.cascade!,leafOnly}})}/><Input label="此来源最大层数" type="number" min={1} max={10} value={String(entry.cascade.maxDepth??10)} onChange={depth=>update(index,{cascade:{...entry.cascade!,maxDepth:Number(depth)}})}/></div>}
    </section>;})}
    {directory.error&&<p className="text-caption text-destructive">{directory.error}</p>}
  </section>;
}
