import {choiceLabel} from "./choices";
import { Button,FieldSelect,Input } from "@/shared/ui";
import type { LowcodeField } from "./field-model";
import { compatibleRuleFields,defaultRuleValue,ruleOperators,ruleOperatorLabels,type RuleOperator } from "./rules";
import { filterGroup,type RelationFilter } from "./relation-filters";
export function RelationFilterEditor({value,onChange,targets,sources,disabled}:{value?:RelationFilter;onChange:(value:RelationFilter|undefined)=>void;targets:LowcodeField[];sources:LowcodeField[];disabled?:boolean}) {
  const eligible=targets.filter(field=>!["relation","lookup"].includes(field.type));
  function render(rule:RelationFilter,change:(next:RelationFilter)=>void,depth:number) {
    if(filterGroup(rule))return <div className="space-y-3 rounded-control border border-border p-3"><FieldSelect label="筛选组合" value={rule.operator} options={[{value:"AND",label:"全部满足"},{value:"OR",label:"任一满足"}]} onChange={operator=>change({...rule,operator:operator as "AND"|"OR"})}/>{rule.conditions.map((child,index)=><div key={index} className="space-y-2 border-l-2 border-border pl-2">{render(child,next=>change({...rule,conditions:rule.conditions.map((item,i)=>i===index?next:item)}),depth+1)}<Button size="sm" variant="ghost" disabled={disabled||rule.conditions.length<=1} onClick={()=>change({...rule,conditions:rule.conditions.filter((_,i)=>i!==index)})}>删除此条件</Button></div>)}<Button size="sm" variant="outline" disabled={disabled||depth>=4||rule.conditions.length>=8||!eligible.length} onClick={()=>change({...rule,conditions:[...rule.conditions,{fieldId:eligible[0].id,operator:"NOT_EMPTY"}]})}>添加筛选条件</Button></div>;
    const target=eligible.find(field=>field.id===rule.fieldId),empty=rule.operator==="EMPTY"||rule.operator==="NOT_EMPTY",compatible=target?sources.filter(field=>compatibleRuleFields(target,field,rule.operator)):[];
    return <div className="space-y-2"><FieldSelect label="目标筛选字段" value={rule.fieldId} options={eligible.map(field=>({value:field.id,label:field.label}))} onChange={fieldId=>change({fieldId,operator:"NOT_EMPTY"})}/><FieldSelect label="筛选比较方式" value={rule.operator} options={ruleOperators(target).map(operator=>({value:operator,label:ruleOperatorLabels[operator]}))} onChange={operator=>change({fieldId:rule.fieldId,operator:operator as RuleOperator,...(["EMPTY","NOT_EMPTY"].includes(operator)?{}:{value:defaultRuleValue(target)})})}/>
      {!empty&&<><FieldSelect label="筛选比较来源" value={rule.sourceFieldId?"source":"constant"} options={[{value:"constant",label:"固定值"},...(compatible.length?[{value:"source",label:"当前表单字段"}]:[])]} onChange={source=>change(source==="source"?{fieldId:rule.fieldId,operator:rule.operator,sourceFieldId:compatible[0].id}:{fieldId:rule.fieldId,operator:rule.operator,value:defaultRuleValue(target)})}/>{rule.sourceFieldId?<FieldSelect label="当前表单来源字段" value={rule.sourceFieldId} options={compatible.map(field=>({value:field.id,label:field.label}))} onChange={sourceFieldId=>change({...rule,sourceFieldId})}/>:target?.type==="checkbox"?<FieldSelect label="筛选固定值" value={String(rule.value??false)} options={[{value:"true",label:"是"},{value:"false",label:"否"}]} onChange={value=>change({...rule,value:value==="true"})}/>:target?.type==="select"?<FieldSelect label="筛选固定值" value={String(rule.value??"")} options={(target.options??[]).map(value=>({value,label:choiceLabel(target,value)}))} onChange={value=>change({...rule,value})}/>:<Input label="筛选固定值" type={typeof defaultRuleValue(target)==="number"?"number":"text"} value={String(rule.value??"")} onChange={value=>change({...rule,value:typeof defaultRuleValue(target)==="number"?Number(value):value})}/>}</>}
      <Button variant="ghost" size="sm" disabled={disabled||depth>=4} onClick={()=>change({operator:"AND",conditions:[rule]})}>组合筛选条件</Button>
    </div>;
  }
  return <fieldset disabled={disabled} className="space-y-3 border-t border-border pt-3"><h4 className="text-caption font-medium">关联记录筛选</h4>{value?render(value,onChange,1):<Button size="sm" variant="outline" disabled={disabled||!eligible.length} onClick={()=>onChange({fieldId:eligible[0].id,operator:"NOT_EMPTY"})}>添加筛选</Button>}{value&&<Button size="sm" variant="ghost" onClick={()=>onChange(undefined)}>移除筛选</Button>}<p className="text-caption leading-5 text-muted-foreground">来源未填写时动态条件不匹配；服务端会校验所选记录。筛选不会授予目标记录权限。</p></fieldset>;
}
