export const defaultSerialTemplate = "{YYYY}{MM}{DD}-{HH}{mm}{ss}-{RAND:8}";
export const serialTokens = ["{YYYY}", "{YY}", "{MM}", "{DD}", "{HH}", "{mm}", "{ss}", "{SSS}", "{RAND:8}", "{DIGITS:6}", "{SEQ:4}"];
const tokenPattern = /\{(YYYY|YY|MM|DD|HH|mm|ss|SSS|(?:RAND|DIGITS):(?:[4-9]|[12][0-9]|3[0-2])|SEQ:(?:[4-9]|1[0-2]))\}/g;
export function serialTemplateError(template: string): string {
  if (!template.trim() || [...template].length > 128) return "编号模板需要 1 至 128 个字符";
  const expanded = template.replace(tokenPattern, (_, token: string) => "0".repeat(token.includes(":") ? Number(token.split(":")[1]) : token.length));
  if (/[{}]/.test(expanded)) return "占位符无效；随机码支持 4 至 32 位，流水号支持 4 至 12 位";
  if ([...expanded].length > 128) return "生成后的编号不能超过 128 个字符";
  return "";
}
/** Design-time example only. Persisted identifiers are generated by the server. */
export function serialExample(template: string, now = new Date()): string {
  if (serialTemplateError(template)) return "";
  const parts = Object.fromEntries(new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Shanghai", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit", hourCycle: "h23" }).formatToParts(now).map((part) => [part.type, part.value]));
  const values: Record<string, string> = { YYYY: parts.year, YY: parts.year.slice(-2), MM: parts.month, DD: parts.day, HH: parts.hour, mm: parts.minute, ss: parts.second, SSS: String(now.getMilliseconds()).padStart(3, "0") };
  return template.replace(tokenPattern, (_, token: string) => values[token] ?? (token.startsWith("SEQ:") ? "1".padStart(Number(token.split(":")[1]), "0") : (token.startsWith("DIGITS") ? "0123456789" : "A7K2M9P4Q6R8T3V5").repeat(4).slice(0, Number(token.split(":")[1]))));
}
